// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgPolkadotLogoMono = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={24} height={32} viewBox="0 0 24 32" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <g clipPath="url(#polkadot-logo-mono_svg__clip0)" fill="#52616B">
      <path d="M12.16 0C5.475.027.063 5.439.037 12.122c0 1.339.216 2.669.64 3.938a1.734 1.734 0 002.132 1.063 1.726 1.726 0 001.03-2.125 8 8 0 01-.471-3.09 8.745 8.745 0 119.27 8.991s-1.7.104-2.547.207a8.784 8.784 0 00-.927.184.112.112 0 01-.158.002l-.002-.002a.111.111 0 010-.135l.264-1.437 1.598-7.188a1.662 1.662 0 10-3.25-.695S3.815 29.428 3.815 29.587a1.597 1.597 0 001.183 1.949h.088a1.596 1.596 0 001.956-1.19.412.412 0 010-.08c.047-.207.527-2.548.527-2.548a4.312 4.312 0 013.569-3.394c.367-.056 1.909-.16 1.909-.16A12.115 12.115 0 0012.16 0z" />
      <path d="M12.896 27.951a2.02 2.02 0 00-2.39 1.566l-.006.031a2.012 2.012 0 001.538 2.395l.003.001h.057a1.98 1.98 0 002.39-1.46c.002-.008.003-.017.006-.024v-.111a2.095 2.095 0 00-1.598-2.398z" />
    </g>
    <defs>
      <clipPath id="polkadot-logo-mono_svg__clip0">
        <path fill="#fff" transform="translate(.037)" d="M0 0h23.924v32H0z" />
      </clipPath>
    </defs>
  </svg>
)
