// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgActionPlayAlt = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" ref={ref} {...props}>
    <path d="m4 3 4.5 2.5L13 8l-4.5 2.5L4 13V3Z" fill="#F4F6F8" />
  </svg>
))
SvgActionPlayAlt.displayName = 'SvgActionPlayAlt'
const Memo = memo(SvgActionPlayAlt)
export { Memo as SvgActionPlayAlt }
