// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { SVGProps, memo } from 'react'

const SvgActionClosedCaptions = (props: SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M0 3a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v10a1 1 0 0 1-1 1H1a1 1 0 0 1-1-1V3Zm4 9a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h3v2H4v4h3v2H4Zm5-2a2 2 0 0 0 2 2h3v-2h-3V6h3V4h-3a2 2 0 0 0-2 2v4Z"
      fill="#F4F6F8"
    />
  </svg>
)

const Memo = memo(SvgActionClosedCaptions)
export { Memo as SvgActionClosedCaptions }
