// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgActionHide = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" ref={ref} {...props}>
    <path
      d="m3.707 2.293 10 10-1.414 1.414-10-10 1.414-1.414ZM8 3c-.353 0-.691.025-1.015.071l6.862 6.861C14.64 8.898 15 8 15 8s-2-5-7-5ZM8 13c-5 0-7-5-7-5s.36-.898 1.153-1.932l6.862 6.86A7.136 7.136 0 0 1 8 13Z"
      fill="#F4F6F8"
    />
  </svg>
))
SvgActionHide.displayName = 'SvgActionHide'
const Memo = memo(SvgActionHide)
export { Memo as SvgActionHide }
