// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'
import { SVGProps, memo } from 'react'

const SvgActionImageFile = (props: SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M2 3a1 1 0 0 1 1-1h10a1 1 0 0 1 1 1v10a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V3Zm2 7v2h8v-2L9 7l-5 3Zm1-6a1 1 0 1 0 0 2 1 1 0 0 0 0-2Z"
      fill="#F4F6F8"
    />
  </svg>
)

const Memo = memo(SvgActionImageFile)
export { Memo as SvgActionImageFile }
