// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'
import { SVGProps, memo } from 'react'

const SvgActionChevronB = (props: SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="m8 9.586 5.293-5.293 1.414 1.414L8 12.414 1.293 5.707l1.414-1.414L8 9.586Z"
      fill="#F4F6F8"
    />
  </svg>
)

const Memo = memo(SvgActionChevronB)
export { Memo as SvgActionChevronB }
