// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { SVGProps, memo } from 'react'

const SvgActionReactionDislike = (props: SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      d="M14 8h-2V2h2v6ZM11 10l-2 4H8v-4H3.72a1.72 1.72 0 0 1-1.632-2.265l1.456-4.367A2 2 0 0 1 5.442 2H11v8Z"
      fill="#F4F6F8"
    />
  </svg>
)

const Memo = memo(SvgActionReactionDislike)
export { Memo as SvgActionReactionDislike }
