// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { SVGProps, memo } from 'react'

const SvgActionBidCancel = (props: SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      d="M9 1.75a.75.75 0 0 0-1.5 0v4.336l-1-1V2.75a.75.75 0 0 0-1.5 0v.836L2.707 1.293 1.293 2.707l12 12 1.414-1.414-1.194-1.195c.126-.292.225-.6.293-.921l.024-.114c.113-.538.17-1.086.17-1.636V3.75a.75.75 0 0 0-1.5 0V8h-1V2.75a.75.75 0 0 0-1.5 0V8h-.586L9 7.586V1.75ZM10.34 14.836c-.4.107-.818.164-1.247.164a5.78 5.78 0 0 1-4.809-2.573l-2.13-3.195A.921.921 0 0 1 2 8.722c0-.822.993-1.232 1.573-.652l6.767 6.766Z"
      fill="#F4F6F8"
    />
  </svg>
)

const Memo = memo(SvgActionBidCancel)
export { Memo as SvgActionBidCancel }
