// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'
import { SVGProps, memo } from 'react'

const SvgActionPlayAlt = (props: SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="m4 3 4.5 2.5L13 8l-4.5 2.5L4 13V3Z" fill="#F4F6F8" />
  </svg>
)

const Memo = memo(SvgActionPlayAlt)
export { Memo as SvgActionPlayAlt }
