// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'
import { SVGProps, memo } from 'react'

const SvgActionResize = (props: SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      d="M5 13.485 6.414 14.9 14.9 6.414 13.485 5 5 13.485ZM11 13.829l1.414 1.414 2.829-2.829L13.828 11 11 13.829Z"
      fill="#F4F6F8"
    />
  </svg>
)

const Memo = memo(SvgActionResize)
export { Memo as SvgActionResize }
