// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgActionHide = React.memo((props: React.SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      d="M3.707 2.293l10 10-1.414 1.414-10-10 1.414-1.414zM8 3c-.353 0-.691.025-1.015.071l6.862 6.861C14.64 8.898 15 8 15 8s-2-5-7-5zM8 13c-5 0-7-5-7-5s.36-.898 1.153-1.932l6.862 6.86A7.136 7.136 0 018 13z"
      fill="#F4F6F8"
    />
  </svg>
))
SvgActionHide.displayName = 'SvgActionHide'
