// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'
import { SVGProps, memo } from 'react'

const SvgActionEmbed = (props: SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M6.707 11.293 3.414 8l3.293-3.293-1.414-1.414-4 4L.586 8l.707.707 4 4 1.414-1.414Zm2.586-6.586L12.586 8l-3.293 3.293 1.414 1.414 4-4L15.414 8l-.707-.707-4-4-1.414 1.414Z"
      fill="#F4F6F8"
    />
  </svg>
)

const Memo = memo(SvgActionEmbed)
export { Memo as SvgActionEmbed }
