// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { SVGProps, memo } from 'react'

const SvgActionBid = (props: SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      d="M9 1.75a.75.75 0 0 0-1.5 0V8h-1V2.75a.75.75 0 0 0-1.5 0V9.5L3.573 8.07C2.993 7.49 2 7.9 2 8.721c0 .182.054.36.155.511l2.13 3.195A5.78 5.78 0 0 0 9.092 15a4.816 4.816 0 0 0 4.713-3.823l.024-.114A7.93 7.93 0 0 0 14 9.427V3.75a.75.75 0 0 0-1.5 0V8h-1V2.75a.75.75 0 0 0-1.5 0V8H9V1.75Z"
      fill="#F4F6F8"
    />
  </svg>
)

const Memo = memo(SvgActionBid)
export { Memo as SvgActionBid }
