// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { SVGProps, memo } from 'react'

const SvgActionShare = (props: SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M15 8 8 3v3H6.65C3 6 1 8 1 10v2h2v-1c0-.552.445-1 .997-1H8v3l7-5Z"
      fill="#F4F6F8"
    />
  </svg>
)

const Memo = memo(SvgActionShare)
export { Memo as SvgActionShare }
