// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'
import { SVGProps, memo } from 'react'

const SvgActionBid = (props: SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      d="M13.16 2.854a.8.8 0 0 0-.593.272.979.979 0 0 0-.245.656v3.4h-.56V2.544a.98.98 0 0 0-.246-.655.801.801 0 0 0-.593-.272.8.8 0 0 0-.594.272.979.979 0 0 0-.245.655v4.636h-.56V1.927a.979.979 0 0 0-.246-.655A.801.801 0 0 0 8.685 1a.801.801 0 0 0-.594.272.979.979 0 0 0-.245.655v5.254h-.56V2.545a.979.979 0 0 0-.246-.655.801.801 0 0 0-.593-.272.801.801 0 0 0-.594.272.979.979 0 0 0-.245.655V9.5L4 8c-.5-.5-1.274-.453-1.7 0-.513.546-.428 1.383.085 1.929l2.86 3.042C6.466 14.271 8.123 15 9.85 15c2.29 0 4.147-1.975 4.147-4.411L14 3.782a.979.979 0 0 0-.246-.656.8.8 0 0 0-.593-.272Z"
      fill="#F4F6F8"
    />
  </svg>
)

const Memo = memo(SvgActionBid)
export { Memo as SvgActionBid }
