// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { SVGProps, memo } from 'react'

const SvgActionReactionLike = (props: SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      d="M2 8h2v6H2V8ZM5 6l2-4h1v4h4.28a1.72 1.72 0 0 1 1.632 2.265l-1.456 4.367A2 2 0 0 1 10.559 14H5V6Z"
      fill="#F4F6F8"
    />
  </svg>
)

const Memo = memo(SvgActionReactionLike)
export { Memo as SvgActionReactionLike }
