// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'
import { SVGProps, memo } from 'react'

const SvgActionZoomOut = (props: SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M10.478 11.892a6 6 0 1 1 1.414-1.414L15 13.584 13.584 15l-3.106-3.107Zm-7.477-3.89h8v-2h-8v2Z"
      fill="#F4F6F8"
    />
  </svg>
)

const Memo = memo(SvgActionZoomOut)
export { Memo as SvgActionZoomOut }
