// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgActionZoomIn = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" ref={ref} {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M10.478 11.892a6 6 0 1 1 1.414-1.414L15 13.584 13.584 15l-3.106-3.107Zm-7.477-3.89h3v3h2v-3h3v-2h-3v-3h-2v3h-3v2Z"
      fill="#F4F6F8"
    />
  </svg>
))
SvgActionZoomIn.displayName = 'SvgActionZoomIn'
const Memo = memo(SvgActionZoomIn)
export { Memo as SvgActionZoomIn }
