// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { SVGProps, memo } from 'react'

const SvgActionLinkUrl = (props: SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      d="M8.464 2.121a3.828 3.828 0 0 1 5.415 5.415l-2.343 2.343a3.828 3.828 0 0 1-5.415 0l1.415-1.415a1.828 1.828 0 0 0 2.586 0l2.342-2.343A1.828 1.828 0 0 0 9.88 3.536l-.672.671-1.414-1.414.671-.672Z"
      fill="#F4F6F8"
    />
    <path
      d="M7.172 5c1.057 0 2.014.429 2.707 1.121L8.464 7.536a1.828 1.828 0 0 0-2.586 0L3.537 9.879a1.828 1.828 0 0 0 2.585 2.585l.672-.671 1.414 1.414-.671.672A3.829 3.829 0 0 1 2.12 8.464l2.343-2.343A3.828 3.828 0 0 1 7.172 5Z"
      fill="#F4F6F8"
    />
  </svg>
)

const Memo = memo(SvgActionLinkUrl)
export { Memo as SvgActionLinkUrl }
