// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgActionBulb = React.memo((props: React.SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      d="M13 6a5.001 5.001 0 01-3 4.584V12H6v-1.416A5.001 5.001 0 018 1a5 5 0 015 5zM8 15a2 2 0 002-2H6a2 2 0 002 2z"
      fill="#F4F6F8"
    />
  </svg>
))
SvgActionBulb.displayName = 'SvgActionBulb'
