// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgActionPlayAlt = React.memo((props: React.SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M4 3l4.5 2.5L13 8l-4.5 2.5L4 13V3z" fill="#F4F6F8" />
  </svg>
))
SvgActionPlayAlt.displayName = 'SvgActionPlayAlt'
