// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgActionAddImage = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" ref={ref} {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M11.667 4 11 2H5l-.667 2H2a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V5a1 1 0 0 0-1-1h-2.333ZM7 5h2v3h3v2H9v3H7v-3H4V8h3V5Z"
      fill="#F4F6F8"
    />
  </svg>
))
SvgActionAddImage.displayName = 'SvgActionAddImage'
const Memo = memo(SvgActionAddImage)
export { Memo as SvgActionAddImage }
