// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'
import { SVGProps, memo } from 'react'

const SvgActionNotifications = (props: SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M8 1a5 5 0 0 1 5 5v3a1 1 0 0 0 1 1h.5a.5.5 0 0 1 0 1h-13a.5.5 0 1 1 0-1H2a1 1 0 0 0 1-1V6a5 5 0 0 1 5-5Zm0 14a3 3 0 0 1-3-3h6a3 3 0 0 1-3 3Z"
      fill="#F4F6F8"
    />
  </svg>
)

const Memo = memo(SvgActionNotifications)
export { Memo as SvgActionNotifications }
