// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { SVGProps, memo } from 'react'

const SvgActionLinkUrl = (props: SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M8.586 2a3.414 3.414 0 0 1 4.828 0l.586.586a3.414 3.414 0 0 1 0 4.828L11.414 10a3.414 3.414 0 0 1-4.828 0l-.293-.293 1.414-1.414.293.293a1.414 1.414 0 0 0 2 0L12.586 6a1.414 1.414 0 0 0 0-2L12 3.414a1.414 1.414 0 0 0-2 0l-.293.293a1 1 0 0 1-1.414-1.414L8.586 2Zm-4 4a3.414 3.414 0 0 1 4.828 0l.293.293-1.414 1.414L8 7.414a1.414 1.414 0 0 0-2 0L3.414 10a1.414 1.414 0 0 0 0 2l.586.586a1.414 1.414 0 0 0 2 0l.293-.293a1 1 0 0 1 1.414 1.414L7.414 14a3.414 3.414 0 0 1-4.828 0L2 13.414a3.414 3.414 0 0 1 0-4.828L4.586 6Z"
      fill="#F4F6F8"
    />
  </svg>
)

const Memo = memo(SvgActionLinkUrl)
export { Memo as SvgActionLinkUrl }
