// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'
import { SVGProps, memo } from 'react'

const SvgActionPause = (props: SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M7 2H3v12h4V2ZM13 2H9v12h4V2Z" fill="#F4F6F8" />
  </svg>
)

const Memo = memo(SvgActionPause)
export { Memo as SvgActionPause }
