// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgActionMore = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" ref={ref} {...props}>
    <path d="M7 1h2v2H7V1ZM7 7h2v2H7V7ZM7 13h2v2H7v-2Z" fill="#F4F6F8" />
  </svg>
))
SvgActionMore.displayName = 'SvgActionMore'
const Memo = memo(SvgActionMore)
export { Memo as SvgActionMore }
