// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgActionBuyNow = React.memo((props: React.SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M3 1a1 1 0 00-1 1v12a1 1 0 001 1h10a1 1 0 001-1V2a1 1 0 00-1-1H3zm5 5a2 2 0 01-2-2H4a4 4 0 108 0h-2a2 2 0 01-2 2z"
      fill="#F4F6F8"
    />
  </svg>
))
SvgActionBuyNow.displayName = 'SvgActionBuyNow'
