// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { SVGProps, memo } from 'react'

const SvgActionChevronR = (props: SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M9.586 8 4.293 2.707l1.414-1.414L12.414 8l-6.707 6.707-1.414-1.414L9.586 8Z"
      fill="#F4F6F8"
    />
  </svg>
)

const Memo = memo(SvgActionChevronR)
export { Memo as SvgActionChevronR }
