// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { SVGProps, memo } from 'react'

const SvgActionShoppingCart = (props: SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M3 1H1v2h2l1.81 7.242a1 1 0 0 0 .97.758h6.791a1 1 0 0 0 .962-.725l1.428-5A1 1 0 0 0 14 4H5l-.772-2.316A1 1 0 0 0 3.279 1H3Zm4 12.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0Zm4.5 1.5a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3Z"
      fill="#F4F6F8"
    />
  </svg>
)

const Memo = memo(SvgActionShoppingCart)
export { Memo as SvgActionShoppingCart }
