// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { SVGProps, memo } from 'react'

const SvgActionPlus = (props: SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M7 2v5H2v2h5v5h2V9h5V7H9V2H7Z" fill="#F4F6F8" />
  </svg>
)

const Memo = memo(SvgActionPlus)
export { Memo as SvgActionPlus }
