// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgActionChangePrice = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" ref={ref} {...props}>
    <path
      d="M10 4.414 8.707 5.707 7.293 4.293 11 .586l3.707 3.707-1.414 1.414L12 4.414V8h-2V4.414ZM6 8H4v3.586l-1.293-1.293-1.414 1.414L5 15.414l3.707-3.707-1.414-1.414L6 11.586V8Z"
      fill="#F4F6F8"
    />
  </svg>
))
SvgActionChangePrice.displayName = 'SvgActionChangePrice'
const Memo = memo(SvgActionChangePrice)
export { Memo as SvgActionChangePrice }
