// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { SVGProps, memo } from 'react'

const SvgActionResize = (props: SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M14 7a1 1 0 0 0-1.707-.707l-5 5A1 1 0 0 0 8 13h5a1 1 0 0 0 1-1V7Z"
      fill="#F4F6F8"
    />
  </svg>
)

const Memo = memo(SvgActionResize)
export { Memo as SvgActionResize }
