// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'
import { SVGProps, memo } from 'react'

const SvgActionBidCancel = (props: SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <g clipPath="url(#a)" fill="#F4F6F8">
      <path d="M13.16 2.854a.8.8 0 0 0-.593.272.979.979 0 0 0-.245.656v3.4h-.56V2.544a.98.98 0 0 0-.246-.655.801.801 0 0 0-.593-.272.8.8 0 0 0-.594.272.979.979 0 0 0-.245.655v4.636h-.074l-.486-.485V1.927a.979.979 0 0 0-.246-.655A.801.801 0 0 0 8.685 1a.801.801 0 0 0-.594.272.979.979 0 0 0-.245.655v3.09l-.56-.56V2.546a.979.979 0 0 0-.246-.655.801.801 0 0 0-.593-.272.801.801 0 0 0-.594.272.979.979 0 0 0-.245.655v.234L4.12 1.293 2.707 2.707l.705.705.002-.002 10 10-.002.002 1.295 1.295 1.414-1.414-2.155-2.156c.02-.18.031-.363.031-.548L14 3.782a.979.979 0 0 0-.246-.656.8.8 0 0 0-.593-.272ZM11.709 14.533 5.608 8.432V9.5L4 8c-.5-.5-1.274-.453-1.7 0-.513.546-.428 1.383.085 1.929l2.86 3.042C6.466 14.271 8.123 15 9.85 15c.668 0 1.3-.168 1.859-.467Z" />
    </g>
    <defs>
      <clipPath id="a">
        <path fill="#fff" d="M0 0h16v16H0z" />
      </clipPath>
    </defs>
  </svg>
)

const Memo = memo(SvgActionBidCancel)
export { Memo as SvgActionBidCancel }
