// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'
import { SVGProps, memo } from 'react'

const SvgActionSell = (props: SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      d="m8.047 1 5.72 5.544c.15.144.233.34.233.544 0 .204-.084.4-.233.544L12.72 8.67 7.06 3H3.682V1h4.365Z"
      fill="#F4F6F8"
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="m6.23 5 5.545 5.544a.77.77 0 0 1 0 1.088l-3.143 3.143a.77.77 0 0 1-1.088 0L2 9.23V5h4.23ZM3.88 7.947a.77.77 0 1 0 .855-1.279.77.77 0 0 0-.855 1.28Z"
      fill="#F4F6F8"
    />
  </svg>
)

const Memo = memo(SvgActionSell)
export { Memo as SvgActionSell }
