// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { SVGProps, memo } from 'react'

const SvgActionAddVideo = (props: SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M0 3a1 1 0 0 1 1-1h10a1 1 0 0 1 1 1v4l3-3h1v8h-1l-3-3v4a1 1 0 0 1-1 1H1a1 1 0 0 1-1-1V3Zm7 1H5v3H2v2h3v3h2V9h3V7H7V4Z"
      fill="#F4F6F8"
    />
  </svg>
)

const Memo = memo(SvgActionAddVideo)
export { Memo as SvgActionAddVideo }
