// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { SVGProps, memo } from 'react'

const SvgAlertsSuccess24 = (props: SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M12 22c5.523 0 10-4.477 10-10S17.523 2 12 2 2 6.477 2 12s4.477 10 10 10Zm4.707-12.293-1.414-1.414L10 13.586l-1.293-1.293-1.414 1.414L10 16.414l6.707-6.707Z"
      fill="#0EB152"
    />
  </svg>
)

const Memo = memo(SvgAlertsSuccess24)
export { Memo as SvgAlertsSuccess24 }
