// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'
import { SVGProps, memo } from 'react'

const SvgCategoriesNewsAndPolitics = (props: SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M1 4a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v13a3 3 0 1 0 6 0V9h2v8a5 5 0 0 1-5 5H6a5 5 0 0 1-5-5V4Zm5 16a3 3 0 0 1-3-3V4h10v13c0 1.126.372 2.164 1 3H6ZM19 7V6h-2v11h2V7ZM5 8h6V6H5v2Zm6 4H5v-2h6v2Zm-6 4h2v-2H5v2Z"
      fill="#F4F6F8"
    />
  </svg>
)

const Memo = memo(SvgCategoriesNewsAndPolitics)
export { Memo as SvgCategoriesNewsAndPolitics }
