// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { SVGProps, memo } from 'react'

const SvgCategoriesNonprofitsAndActivism = (props: SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M10 5a1 1 0 0 0-2 0v2a1 1 0 0 0 2 0V5Zm3 3a1 1 0 0 1-1-1V4a1 1 0 1 1 2 0v3a1 1 0 0 1-1 1Zm2.493-5.67A2.997 2.997 0 0 0 13 1a2.998 2.998 0 0 0-2.529 1.385 2.998 2.998 0 0 0-4 1A3 3 0 0 0 2 6v8a9 9 0 0 0 9 9h2v-2h-2a7 7 0 0 1-7-7V9.83c.313.11.65.17 1 .17.768 0 1.47-.289 2-.764.53.475 1.232.764 2 .764.462 0 .9-.105 1.291-.291A3 3 0 0 0 13 14h2.809c.095 0 .126.028.138.04a.232.232 0 0 1 .062.133.233.233 0 0 1-.02.146c-.009.014-.03.05-.122.077l-1.17.35A2.381 2.381 0 0 0 13 17.029V19h2v-1.972c0-.169.11-.317.272-.365l1.17-.352c2.43-.728 1.904-4.311-.633-4.311H13a1 1 0 1 1 0-2h6a1 1 0 0 1 1 1v3a7.003 7.003 0 0 1-5 6.71v2.067c4.008-.91 7-4.494 7-8.777v-3a3.001 3.001 0 0 0-2-2.83V5a3 3 0 0 0-3-3h-.182c-.479 0-.93.12-1.325.33ZM4 6v1a1 1 0 0 0 2 0V6a1 1 0 0 0-2 0Zm14-1a1 1 0 1 0-2 0v2a1 1 0 1 0 2 0V5Z"
      fill="#F4F6F8"
    />
  </svg>
)

const Memo = memo(SvgCategoriesNonprofitsAndActivism)
export { Memo as SvgCategoriesNonprofitsAndActivism }
