// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { SVGProps, memo } from 'react'

const SvgControlsCaptionsSolid = (props: SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M3 3a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h18a2 2 0 0 0 2-2V5a2 2 0 0 0-2-2H3Zm2 6a2 2 0 0 1 2-2h2a2 2 0 0 1 2 2v2H9V9H7v6h2v-2h2v2a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V9Zm8 0a2 2 0 0 1 2-2h2a2 2 0 0 1 2 2v2h-2V9h-2v6h2v-2h2v2a2 2 0 0 1-2 2h-2a2 2 0 0 1-2-2V9Z"
      fill="#F4F6F8"
    />
  </svg>
)

const Memo = memo(SvgControlsCaptionsSolid)
export { Memo as SvgControlsCaptionsSolid }
