// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { SVGProps, memo } from 'react'

const SvgControlsReplay = (props: SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      d="M6.083 11A6.002 6.002 0 0 1 18 12a6 6 0 0 1-10.286 4.2l-1.428 1.399A8 8 0 1 0 4.062 11H2l3 4 3-4H6.083Z"
      fill="#F4F6F8"
    />
  </svg>
)

const Memo = memo(SvgControlsReplay)
export { Memo as SvgControlsReplay }
