// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgControlsSeekForward5 = React.memo((props: React.SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M12 4a8 8 0 018 8h2c0-5.523-4.477-10-10-10v2zM8 9l4 3-4 3V9zm5 0l4 3-4 3V9z"
      fill="#F4F6F8"
    />
  </svg>
))
SvgControlsSeekForward5.displayName = 'SvgControlsSeekForward5'
