// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { SVGProps, memo } from 'react'

const SvgControlsBack = (props: SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M7 6.586 1.586 12 7 17.414 8.414 16l-3-3H22v-2H5.414l3-3L7 6.586Z" fill="#F4F6F8" />
  </svg>
)

const Memo = memo(SvgControlsBack)
export { Memo as SvgControlsBack }
