// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgControlsSeekForward5 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" ref={ref} {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M12 4a8 8 0 0 1 8 8h2c0-5.523-4.477-10-10-10v2ZM8 9l4 3-4 3V9Zm5 0 4 3-4 3V9Z"
      fill="#F4F6F8"
    />
  </svg>
))
SvgControlsSeekForward5.displayName = 'SvgControlsSeekForward5'
const Memo = memo(SvgControlsSeekForward5)
export { Memo as SvgControlsSeekForward5 }
