// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { SVGProps, memo } from 'react'

const SvgControlsPause = (props: SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path fillRule="evenodd" clipRule="evenodd" d="M6 20V4h4v16H6ZM14 20V4h4v16h-4Z" fill="#F4F6F8" />
  </svg>
)

const Memo = memo(SvgControlsPause)
export { Memo as SvgControlsPause }
