// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgControlsPlaylist = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" ref={ref} {...props}>
    <path d="M2 7h16v2H2V7ZM18 11H2v2h16v-2ZM22 18l-5-3v6l5-3ZM15 15H2v2h13v-2Z" fill="#F4F6F8" />
  </svg>
))
SvgControlsPlaylist.displayName = 'SvgControlsPlaylist'
const Memo = memo(SvgControlsPlaylist)
export { Memo as SvgControlsPlaylist }
