// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgControlsPause = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" ref={ref} {...props}>
    <path fillRule="evenodd" clipRule="evenodd" d="M6 20V4h4v16H6ZM14 20V4h4v16h-4Z" fill="#F4F6F8" />
  </svg>
))
SvgControlsPause.displayName = 'SvgControlsPause'
const Memo = memo(SvgControlsPause)
export { Memo as SvgControlsPause }
