// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'
import { SVGProps, memo } from 'react'

const SvgControlsSmallScreen = (props: SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M17 3v4h4v2h-4a2 2 0 0 1-2-2V3h2ZM9 3v4a2 2 0 0 1-2 2H3V7h4V3h2ZM7 21v-4H3v-2h4a2 2 0 0 1 2 2v4H7ZM15 21v-4a2 2 0 0 1 2-2h4v2h-4v4h-2Z"
      fill="#F4F6F8"
    />
  </svg>
)

const Memo = memo(SvgControlsSmallScreen)
export { Memo as SvgControlsSmallScreen }
