// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgControlsCastOutline = React.memo((props: React.SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M1 5a2 2 0 012-2h18a2 2 0 012 2v14a2 2 0 01-2 2H11v-2h10V5H3v6H1V5zm6 16a6 6 0 00-6-6v-2a8 8 0 018 8H7zm-6-2a2 2 0 012 2h2a4 4 0 00-4-4v2z"
      fill="#F4F6F8"
    />
  </svg>
))
SvgControlsCastOutline.displayName = 'SvgControlsCastOutline'
