// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgControlsPlaylistAdd = React.memo((props: React.SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M2 7h13v2H2V7zM2 11h13v2H2v-2zM12 15H2v2h10v-2zM19 15h3v2h-3v3h-2v-3h-3v-2h3v-3h2v3z" fill="#F4F6F8" />
  </svg>
))
SvgControlsPlaylistAdd.displayName = 'SvgControlsPlaylistAdd'
