// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { SVGProps, memo } from 'react'

const SvgControlsSeekBackward10 = (props: SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M12 4a8 8 0 1 0 0 16v2C6.477 22 2 17.523 2 12S6.477 2 12 2v2Zm4 5-4 3 4 3V9Zm-5 0-4 3 4 3V9Z"
      fill="#F4F6F8"
    />
  </svg>
)

const Memo = memo(SvgControlsSeekBackward10)
export { Memo as SvgControlsSeekBackward10 }
