// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'
import { SVGProps, memo } from 'react'

const SvgControlsImageFile = (props: SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="m18 14-4-4-8 4v2h12v-2ZM7 10a1 1 0 1 0 0-2 1 1 0 0 0 0 2Z" fill="#F4F6F8" />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M2 6a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V6Zm18 0H4v12h16V6Z"
      fill="#F4F6F8"
    />
  </svg>
)

const Memo = memo(SvgControlsImageFile)
export { Memo as SvgControlsImageFile }
