// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgControlsZoomOut = React.memo((props: React.SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M14 11V9H6v2h8z" fill="#F4F6F8" />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M1 10a9 9 0 1118 0 9 9 0 01-18 0zm9-7a7 7 0 100 14 7 7 0 000-14z"
      fill="#F4F6F8"
    />
    <path d="M18.707 17.293l4 4-1.414 1.414-4-4 1.414-1.414z" fill="#F4F6F8" />
  </svg>
))
SvgControlsZoomOut.displayName = 'SvgControlsZoomOut'
