// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'
import { SVGProps, memo } from 'react'

const SvgControlsSoundOff = (props: SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      d="M15.326 13.497 12 10.171V4h-2L8.146 6.317 3.929 2.1 2.515 3.515l18 18 1.414-1.415-2.358-2.358A8 8 0 0 0 14 4v2a6 6 0 0 1 4.155 10.327l-1.415-1.414A4 4 0 0 0 14 8v2a2 2 0 0 1 1.326 3.497ZM5.172 9H3a1 1 0 0 0-1 1v4a1 1 0 0 0 1 1h3l4 5h2v-4.172L5.172 9ZM14 18c.057 0 .113 0 .17-.002l1.766 1.766A8.02 8.02 0 0 1 14 20v-2Z"
      fill="#F4F6F8"
    />
  </svg>
)

const Memo = memo(SvgControlsSoundOff)
export { Memo as SvgControlsSoundOff }
