// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgControlsBack = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" ref={ref} {...props}>
    <path d="M7 6.586 1.586 12 7 17.414 8.414 16l-3-3H22v-2H5.414l3-3L7 6.586Z" fill="#F4F6F8" />
  </svg>
))
SvgControlsBack.displayName = 'SvgControlsBack'
const Memo = memo(SvgControlsBack)
export { Memo as SvgControlsBack }
