// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgControlsReplay = React.memo((props: React.SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      d="M6.083 11A6.002 6.002 0 0118 12a6 6 0 01-10.286 4.2l-1.428 1.399A8 8 0 104.062 11H2l3 4 3-4H6.083z"
      fill="#F4F6F8"
    />
  </svg>
))
SvgControlsReplay.displayName = 'SvgControlsReplay'
