// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { SVGProps, memo } from 'react'

const SvgIllustrativePlay = (props: SVGProps<SVGSVGElement>) => (
  <svg width={48} height={48} viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="m30 24-9-6v12l9-6Z" fill="#F4F6F8" />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M24 7C14.611 7 7 14.611 7 24s7.611 17 17 17 17-7.611 17-17S33.389 7 24 7ZM9 24c0-8.284 6.716-15 15-15 8.284 0 15 6.716 15 15 0 8.284-6.716 15-15 15-8.284 0-15-6.716-15-15Z"
      fill="#F4F6F8"
    />
  </svg>
)

const Memo = memo(SvgIllustrativePlay)
export { Memo as SvgIllustrativePlay }
