// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgIllustrativeFileFailed = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg width={48} height={48} viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg" ref={ref} {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M8 5a1 1 0 0 1 1-1h3.8v2H10v2.8H8V5Zm6.7-1h7.6v2h-7.6V4Zm9.5 0H28a1 1 0 0 1 .673.26l4.4 4-1.346 1.48L27.613 6H24.2V4Zm11.073 6.26 4.4 4A1 1 0 0 1 40 15v3.733h-2v-3.29l-4.073-3.703 1.346-1.48ZM8 18.3v-7.6h2v7.6H8Zm0 9.5v-7.6h2v7.6H8Zm32-7.2v7.467h-2V20.6h2ZM8 37.3v-7.6h2v7.6H8Zm32-7.367V37.4h-2v-7.467h2ZM8 43v-3.8h2V42h3v2H9a1 1 0 0 1-1-1Zm32-3.733V43a1 1 0 0 1-1 1h-4v-2h3v-2.733h2ZM23 44h-8v-2h8v2Zm10 0h-8v-2h8v2Z"
      fill="#F4F6F8"
    />
    <path d="M28 15V5l11 10H28Z" fill="#F4F6F8" />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M27.596 4.085a1 1 0 0 1 1.077.175l11 10A1 1 0 0 1 39 16H28a1 1 0 0 1-1-1V5a1 1 0 0 1 .596-.915ZM29 7.261V14h7.413L29 7.26Z"
      fill="#F4F6F8"
    />
    <path
      d="M28.293 24.293 24 28.586l-4.293-4.293-1.414 1.414L22.586 30l-4.293 4.293 1.414 1.414L24 31.414l4.293 4.293 1.414-1.414L25.414 30l4.293-4.293-1.414-1.414Z"
      fill="#F4F6F8"
    />
  </svg>
))
SvgIllustrativeFileFailed.displayName = 'SvgIllustrativeFileFailed'
const Memo = memo(SvgIllustrativeFileFailed)
export { Memo as SvgIllustrativeFileFailed }
