// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'
import { SVGProps, memo } from 'react'

const SvgJoyTokenPrimary48 = (props: SVGProps<SVGSVGElement>) => (
  <svg width={48} height={48} viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M24 44c11.046 0 20-8.954 20-20S35.046 4 24 4 4 12.954 4 24s8.954 20 20 20Zm-.008-12a8 8 0 0 1-8-8h-6c0 7.732 6.268 14 14 14s14-6.268 14-14h-6a8 8 0 0 1-8 8Z"
      fill="url(#paint0_linear_911_327)"
    />
    <defs>
      <linearGradient id="paint0_linear_911_327" x1={24} y1={4} x2={24} y2={44} gradientUnits="userSpaceOnUse">
        <stop stopColor="#7174FF" />
        <stop offset={1} stopColor="#2823A0" />
      </linearGradient>
    </defs>
  </svg>
)

const Memo = memo(SvgJoyTokenPrimary48)
export { Memo as SvgJoyTokenPrimary48 }
