// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'
import { SVGProps, memo } from 'react'

const SvgJoyTokenSilver48 = (props: SVGProps<SVGSVGElement>) => (
  <svg width={48} height={48} viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <g filter="url(#filter0_i_911_334)">
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M24 44c11.046 0 20-8.954 20-20S35.046 4 24 4 4 12.954 4 24s8.954 20 20 20Zm-.008-12a8 8 0 0 1-8-8h-6c0 7.732 6.268 14 14 14s14-6.268 14-14h-6a8 8 0 0 1-8 8Z"
        fill="url(#paint0_linear_911_334)"
      />
    </g>
    <defs>
      <linearGradient id="paint0_linear_911_334" x1={24} y1={4} x2={24} y2={44} gradientUnits="userSpaceOnUse">
        <stop stopColor="#7B8A95" />
        <stop offset={1} stopColor="#424E57" />
      </linearGradient>
      <filter
        id="filter0_i_911_334"
        x={4}
        y={4}
        width={40}
        height={40.5}
        filterUnits="userSpaceOnUse"
        colorInterpolationFilters="sRGB"
      >
        <feFlood floodOpacity={0} result="BackgroundImageFix" />
        <feBlend in="SourceGraphic" in2="BackgroundImageFix" result="shape" />
        <feColorMatrix in="SourceAlpha" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha" />
        <feOffset dy={0.5} />
        <feGaussianBlur stdDeviation={0.25} />
        <feComposite in2="hardAlpha" operator="arithmetic" k2={-1} k3={1} />
        <feColorMatrix values="0 0 0 0 0.70875 0 0 0 0 0.756 0 0 0 0 0.7875 0 0 0 1 0" />
        <feBlend in2="shape" result="effect1_innerShadow_911_334" />
      </filter>
    </defs>
  </svg>
)

const Memo = memo(SvgJoyTokenSilver48)
export { Memo as SvgJoyTokenSilver48 }
