// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgLogoVkOnLight = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" ref={ref} {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M14.76 3H9.24C4.2 3 3 4.2 3 9.24v5.52C3 19.8 4.2 21 9.24 21h5.52C19.8 21 21 19.8 21 14.76V9.24C21 4.2 19.8 3 14.76 3Z"
      fill="#2787F5"
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M17.344 8.719c.397 0 .48.204.397.482-.167.765-1.766 3.018-1.766 3.018-.14.222-.195.333 0 .584.068.096.215.239.382.403.172.168.367.359.522.542.563.634.988 1.17 1.107 1.538.108.37-.08.558-.455.558H16.22c-.352 0-.529-.197-.911-.623-.162-.18-.361-.402-.626-.666-.78-.751-1.113-.849-1.308-.849-.264 0-.343.075-.343.45v1.177c0 .323-.103.51-.937.51-1.39 0-2.919-.843-4.003-2.4-1.627-2.281-2.072-4.005-2.072-4.353 0-.195.075-.371.45-.371H7.78c.336 0 .462.147.588.51.642 1.87 1.724 3.504 2.169 3.504.167 0 .243-.077.243-.5V10.3c-.03-.55-.222-.788-.364-.965-.088-.108-.157-.194-.157-.315 0-.146.125-.301.334-.301h2.062c.278 0 .375.148.375.482v2.6c0 .278.121.376.204.376.167 0 .306-.098.612-.403.946-1.057 1.613-2.684 1.613-2.684.084-.195.238-.371.571-.371h1.313Z"
      fill="#fff"
    />
  </svg>
))
SvgLogoVkOnLight.displayName = 'SvgLogoVkOnLight'
const Memo = memo(SvgLogoVkOnLight)
export { Memo as SvgLogoVkOnLight }
