// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'
import { SVGProps, memo } from 'react'

const SvgSidebarUpload = (props: SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      d="M3 1a2 2 0 0 0-2 2v18a2 2 0 0 0 2 2h10V9.414l3 3L17.414 11 12 5.586 6.586 11 8 12.414l3-3V21H3V3h18v18h-6v2h6a2 2 0 0 0 2-2V3a2 2 0 0 0-2-2H3Z"
      fill="#F4F6F8"
    />
  </svg>
)

const Memo = memo(SvgSidebarUpload)
export { Memo as SvgSidebarUpload }
