// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgSidebarChannel = React.memo((props: React.SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M8 9a4 4 0 118 0 4 4 0 01-8 0zm4-2a2 2 0 100 4 2 2 0 000-4z"
      fill="#F4F6F8"
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M3 1a2 2 0 00-2 2v18a2 2 0 002 2h4v-3a3 3 0 013-3h4a3 3 0 013 3v1H9v2h12a2 2 0 002-2V3a2 2 0 00-2-2H3zm16 20h2V3H3v18h2v-1a5 5 0 015-5h4a5 5 0 015 5v1z"
      fill="#F4F6F8"
    />
  </svg>
))
SvgSidebarChannel.displayName = 'SvgSidebarChannel'
