// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'
import { SVGProps, memo } from 'react'

const SvgSidebarNew = (props: SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      d="M2.314 3.308A.943.943 0 0 1 3 3h18c.245 0 .493.103.686.308.195.207.314.5.314.817v10.75c0 .317-.12.61-.314.817A.942.942 0 0 1 21 16H4v2h17c.816 0 1.585-.345 2.142-.937.556-.59.858-1.378.858-2.188V4.125c0-.81-.302-1.598-.858-2.188A2.942 2.942 0 0 0 21 1H3c-.816 0-1.585.345-2.142.937A3.194 3.194 0 0 0 0 4.125V23h2V4.125c0-.317.12-.61.314-.817Z"
      fill="#F4F6F8"
    />
    <path
      d="M7.116 12.09h1.36V7h-.963c.003.86.027 3.813.027 3.813L5.35 7H4v5.09h.956c0-2.643-.035-3.85-.035-3.85l2.195 3.85ZM12.7 12.09H9.795V7H12.7v.884h-1.835v1.118h1.708v.885h-1.708v1.312H12.7v.892ZM17.498 12.09h1.218L20 7h-1.052l-.642 2.778c-.08.319-.2.957-.249 1.334a15.766 15.766 0 0 0-.23-1.26L17.09 7h-1.012c-.276 1.046-.867 3.44-.97 4.113a16.83 16.83 0 0 0-.244-1.334L14.22 7h-1.053l1.287 5.09h1.215l.68-2.667c.058-.23.202-.934.231-1.198.02.217.184 1.003.235 1.192l.683 2.674Z"
      fill="#F4F6F8"
    />
  </svg>
)

const Memo = memo(SvgSidebarNew)
export { Memo as SvgSidebarNew }
