// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { SVGProps, memo } from 'react'

const SvgSidebarChannels = (props: SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M16 3a4 4 0 1 0 0 8 4 4 0 0 0 0-8Zm-2 4a2 2 0 1 1 4 0 2 2 0 0 1-4 0Z"
      fill="#F4F6F8"
    />
    <path
      d="M6 5a2 2 0 1 0 0 4 2 2 0 0 0 0-4ZM12.5 19H21v-1a3 3 0 0 0-3-3h-4a3 3 0 0 0-3 3v1.5H9V18c0-.343.034-.677.1-1H5v-2h3.991A2.2 2.2 0 0 0 6.8 13H5a2 2 0 0 0-2 2v2H1v-2a4 4 0 0 1 4-4h1.8a4.202 4.202 0 0 1 4.057 3.11A4.98 4.98 0 0 1 14 13h4a5 5 0 0 1 5 5v1a2 2 0 0 1-2 2h-8.5v-2Z"
      fill="#F4F6F8"
    />
  </svg>
)

const Memo = memo(SvgSidebarChannels)
export { Memo as SvgSidebarChannels }
