// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { SVGProps, memo } from 'react'

const SvgSidebarPayments = (props: SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M5 1h14v2H5V1ZM3 7h18v3h-5a4 4 0 0 0 0 8h5v3H3V7Zm18 5h-5a2 2 0 1 0 0 4h5v-4Zm2 6v3a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2h18a2 2 0 0 1 2 2v11Zm-6-3a1 1 0 1 0 0-2 1 1 0 0 0 0 2Z"
      fill="#F4F6F8"
    />
  </svg>
)

const Memo = memo(SvgSidebarPayments)
export { Memo as SvgSidebarPayments }
