// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { SVGProps, memo } from 'react'

const SvgSocialMediaMessengerMonochrome = (props: SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M2.625 11.953C2.625 6.728 6.719 2.86 12 2.86s9.375 3.869 9.375 9.094-4.094 9.094-9.375 9.094c-.949 0-1.859-.125-2.714-.36a.748.748 0 0 0-.5.036l-1.861.822a.75.75 0 0 1-1.053-.664l-.05-1.667a.749.749 0 0 0-.253-.535c-1.824-1.631-2.944-3.993-2.944-6.726Zm6.5-1.707L6.37 14.615c-.264.42.251.892.646.592l2.958-2.245a.562.562 0 0 1 .678-.002l2.19 1.643c.658.493 1.596.32 2.034-.375l2.754-4.37c.264-.419-.252-.891-.646-.592l-2.958 2.245a.563.563 0 0 1-.678.002l-2.19-1.642a1.406 1.406 0 0 0-2.034.375Z"
      fill="#fff"
    />
  </svg>
)

const Memo = memo(SvgSocialMediaMessengerMonochrome)
export { Memo as SvgSocialMediaMessengerMonochrome }
