// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgTierIcon2 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg width={37} height={36} viewBox="0 0 37 36" fill="none" xmlns="http://www.w3.org/2000/svg" ref={ref} {...props}>
    <g clipPath="url(#clip0_1532_4306)">
      <path d="M18 35.993C8.18 35.733.267 27.82.007 18H18v17.993Z" fill="#E7BE2D" />
    </g>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M18.038 16.59V18h-1.41L.038 1.41V0h1.41l16.59 16.59Zm-18-12.27v2.814L10.905 18h2.813L.038 4.32Zm0 8.41V9.9l8.1 8.1h-2.83l-5.27-5.27Zm0 5.27h2.52l-2.52-2.52V18Zm4.32-18h2.814l10.866 10.866v2.814L4.358 0Zm8.41 0h-2.83l8.1 8.1V5.27L12.768 0Zm5.27 2.52L15.518 0h2.52v2.52Z"
      fill="#E7BE2D"
    />
    <g clipPath="url(#clip1_1532_4306)">
      <path d="M18 .007C27.82.267 35.733 8.18 35.993 18H18V.007Z" fill="#E7BE2D" />
    </g>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M36.038 34.59V36h-1.41l-16.59-16.59V18h1.41l16.59 16.59Zm-18-12.27v2.814L28.905 36h2.813l-13.68-13.68Zm0 8.41V27.9l8.1 8.1h-2.83l-5.27-5.27Zm0 5.27h2.52l-2.52-2.52V36Zm4.32-18h2.814l10.866 10.866v2.814L22.358 18Zm8.41 0h-2.83l8.1 8.1v-2.83L30.768 18Zm5.27 2.52L33.518 18h2.52v2.52Z"
      fill="#E7BE2D"
    />
    <defs>
      <clipPath id="clip0_1532_4306">
        <path fill="#fff" transform="rotate(180 9 18)" d="M0 0h18v18H0z" />
      </clipPath>
      <clipPath id="clip1_1532_4306">
        <path fill="#fff" transform="translate(18)" d="M0 0h18v18H0z" />
      </clipPath>
    </defs>
  </svg>
))
SvgTierIcon2.displayName = 'SvgTierIcon2'
const Memo = memo(SvgTierIcon2)
export { Memo as SvgTierIcon2 }
