version: '3.7'
services:
  nginx:
    build:
      context: .
      target: nginx
    ports:
      - "80:80"
    restart: always
  node:
    build:
      context: .
      target: pm2_start
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
