// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgActionNft = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" ref={ref} {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M14.062 4.5 8 1 1.938 4.5v7L8 15l6.062-3.5v-7ZM6 11.464 12 8 6 4.536v6.928Z"
      fill="#fff"
    />
  </svg>
))
SvgActionNft.displayName = 'SvgActionNft'
const Memo = memo(SvgActionNft)
export { Memo as SvgActionNft }
