// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgActionSell = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" ref={ref} {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M1.315 8.762a1.077 1.077 0 0 0 0 1.522l4.4 4.4a1.077 1.077 0 0 0 1.523 0L15 6.925V1H9.077L1.315 8.762Zm11.052-3.636a1.077 1.077 0 1 1-1.197-1.791 1.077 1.077 0 0 1 1.197 1.791Z"
      fill="#F4F6F8"
    />
  </svg>
))
SvgActionSell.displayName = 'SvgActionSell'
const Memo = memo(SvgActionSell)
export { Memo as SvgActionSell }
