// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgActionNotForSale = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" ref={ref} {...props}>
    <path
      d="m1.315 8.762 1.599-1.599 5.923 5.923-1.599 1.599a1.077 1.077 0 0 1-1.523 0l-4.4-4.4a1.077 1.077 0 0 1 0-1.523Z"
      fill="#F4F6F8"
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M10.25 11.672 4.329 5.749l.003-.004-3.038-3.038 1.414-1.414L5.745 4.33 9.077 1H15v5.923l-3.332 3.331 3.039 3.039-1.414 1.414-3.039-3.038-.003.003Zm1.519-6.364a1.077 1.077 0 1 0 0-2.154 1.077 1.077 0 0 0 0 2.154Z"
      fill="#F4F6F8"
    />
  </svg>
))
SvgActionNotForSale.displayName = 'SvgActionNotForSale'
const Memo = memo(SvgActionNotForSale)
export { Memo as SvgActionNotForSale }
