// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgActionExclamation = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" ref={ref} {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M8 14A6 6 0 1 0 8 2a6 6 0 0 0 0 12Zm1-4v2H7v-2h2Zm0-6v5H7V4h2Z"
      fill="#F4F6F8"
    />
  </svg>
))
SvgActionExclamation.displayName = 'SvgActionExclamation'
const Memo = memo(SvgActionExclamation)
export { Memo as SvgActionExclamation }
