// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgActionCrown = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" ref={ref} {...props}>
    <path
      d="M9 3a1 1 0 0 1-.629.929l1.532 3.829a.2.2 0 0 0 .306.085L13.2 5.6a1 1 0 1 1 .525.362l-1.684 5.893a.2.2 0 0 1-.192.145H4.151a.2.2 0 0 1-.192-.145L2.275 5.962A1 1 0 1 1 2.8 5.6l2.991 2.243a.2.2 0 0 0 .306-.085l1.532-3.83A1 1 0 1 1 9 3ZM4 14.167c0-.092.075-.167.167-.167h7.666c.092 0 .167.075.167.167 0 .46-.373.833-.833.833H4.833A.833.833 0 0 1 4 14.167Z"
      fill="#F4F6F8"
    />
  </svg>
))
SvgActionCrown.displayName = 'SvgActionCrown'
const Memo = memo(SvgActionCrown)
export { Memo as SvgActionCrown }
