// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgActionImage = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" ref={ref} {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="m10 3 .667 2H13a1 1 0 0 1 1 1v6a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V6a1 1 0 0 1 1-1h2.333L6 3h4ZM8 7a2 2 0 1 0 0 4 2 2 0 0 0 0-4Z"
      fill="#F4F6F8"
    />
  </svg>
))
SvgActionImage.displayName = 'SvgActionImage'
const Memo = memo(SvgActionImage)
export { Memo as SvgActionImage }
