// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgActionArrowRight = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" ref={ref} {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M12.172 8 6.879 2.707l1.414-1.414L15 8l-6.707 6.707-1.414-1.414L12.172 8Z"
      fill="#F4F6F8"
    />
    <path d="M13 7v2H1V7h12Z" fill="#F4F6F8" />
  </svg>
))
SvgActionArrowRight.displayName = 'SvgActionArrowRight'
const Memo = memo(SvgActionArrowRight)
export { Memo as SvgActionArrowRight }
