// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgActionHeading3 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" ref={ref} {...props}>
    <path
      d="M1 2h2v5h4V2h2v12H7V9H3v5H1V2ZM11.813 8.879a1.67 1.67 0 0 1 2.539-.286c.562.533.616 1.41.124 2.007l-.329.4.33.4a1.475 1.475 0 0 1-.125 2.007 1.67 1.67 0 0 1-2.539-.286l-.229-.344.832-.554.23.344a.67.67 0 0 0 1.018.114.475.475 0 0 0 .04-.646l-.44-.535H12.5v-1h.764l.44-.535a.475.475 0 0 0-.04-.646.67.67 0 0 0-1.019.114l-.229.344-.832-.554.23-.344Z"
      fill="#F4F6F8"
    />
  </svg>
))
SvgActionHeading3.displayName = 'SvgActionHeading3'
const Memo = memo(SvgActionHeading3)
export { Memo as SvgActionHeading3 }
