// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgActionHeading4 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" ref={ref} {...props}>
    <path d="M3 2H1v12h2V9h4v5h2V2H7v5H3V2Z" fill="#F4F6F8" />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M14.5 8h-1.83l-1.57 3.664a.6.6 0 0 0 .551.836H13.5V14h1V8Zm-1 1v2.5h-1.242L13.33 9h.17Z"
      fill="#F4F6F8"
    />
  </svg>
))
SvgActionHeading4.displayName = 'SvgActionHeading4'
const Memo = memo(SvgActionHeading4)
export { Memo as SvgActionHeading4 }
