// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgActionPause = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" ref={ref} {...props}>
    <path d="M7 2H3v12h4V2ZM13 2H9v12h4V2Z" fill="#F4F6F8" />
  </svg>
))
SvgActionPause.displayName = 'SvgActionPause'
const Memo = memo(SvgActionPause)
export { Memo as SvgActionPause }
