// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgActionHeading1 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" ref={ref} {...props}>
    <path
      d="M3 2H1v12h2V9h4v5h2V2H7v5H3V2ZM12.354 10.354 13 9.707V13h-1v1h3v-1h-1V8.524a.51.51 0 0 0-.87-.36l-1.484 1.482.708.707Z"
      fill="#F4F6F8"
    />
  </svg>
))
SvgActionHeading1.displayName = 'SvgActionHeading1'
const Memo = memo(SvgActionHeading1)
export { Memo as SvgActionHeading1 }
