// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgActionComputer = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" ref={ref} {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M3 1a2 2 0 0 0-2 2v6a2 2 0 0 0 2 2h4v2H5a1 1 0 0 0-1 1v1h8v-1a1 1 0 0 0-1-1H9v-2h4a2 2 0 0 0 2-2V3a2 2 0 0 0-2-2H3Zm10 2H3v6h10V3Z"
      fill="#F4F6F8"
    />
  </svg>
))
SvgActionComputer.displayName = 'SvgActionComputer'
const Memo = memo(SvgActionComputer)
export { Memo as SvgActionComputer }
