// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgActionTransfer = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" ref={ref} {...props}>
    <path
      d="M10.998 7a4 4 0 1 0 0 8 4 4 0 0 0 0-8ZM3.29 15h2V4.381l1.372 1.326 1.414-1.414L4.29.586.584 4.293l1.414 1.414L3.29 4.414V15Z"
      fill="#F4F6F8"
    />
  </svg>
))
SvgActionTransfer.displayName = 'SvgActionTransfer'
const Memo = memo(SvgActionTransfer)
export { Memo as SvgActionTransfer }
