// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgActionInformative = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" ref={ref} {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14ZM7 4v2h2V4H7Zm0 3v5h2V7H7Z"
      fill="#F4F6F8"
    />
  </svg>
))
SvgActionInformative.displayName = 'SvgActionInformative'
const Memo = memo(SvgActionInformative)
export { Memo as SvgActionInformative }
