// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgActionMint = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" ref={ref} {...props}>
    <path
      d="M8 1H7v4H2v2a2 2 0 0 1 2 2v1h7.6A2.4 2.4 0 0 0 14 7.6V7a6 6 0 0 0-6-6ZM6 15a2 2 0 1 0 0-4 2 2 0 0 0 0 4ZM12 15a2 2 0 1 0 0-4 2 2 0 0 0 0 4Z"
      fill="#F4F6F8"
    />
  </svg>
))
SvgActionMint.displayName = 'SvgActionMint'
const Memo = memo(SvgActionMint)
export { Memo as SvgActionMint }
