// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgActionUpload = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" ref={ref} {...props}>
    <path
      d="M4.707 7.707 7 5.414V10h2V5.414l2.293 2.293 1.414-1.414L8 1.586 3.293 6.293l1.414 1.414ZM2 12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2v-1h-2v1H4v-1H2v1Z"
      fill="#F4F6F8"
    />
  </svg>
))
SvgActionUpload.displayName = 'SvgActionUpload'
const Memo = memo(SvgActionUpload)
export { Memo as SvgActionUpload }
