// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgActionChevronB = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" ref={ref} {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="m8 9.586 5.293-5.293 1.414 1.414L8 12.414 1.293 5.707l1.414-1.414L8 9.586Z"
      fill="#F4F6F8"
    />
  </svg>
))
SvgActionChevronB.displayName = 'SvgActionChevronB'
const Memo = memo(SvgActionChevronB)
export { Memo as SvgActionChevronB }
