// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgActionVerified = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" ref={ref} {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M8.698 1.28a1 1 0 0 0-1.462 0l-1.1 1.179a1 1 0 0 1-.765.316L3.76 2.721a1 1 0 0 0-1.034 1.033l.055 1.612a1 1 0 0 1-.317.764l-1.178 1.1a1 1 0 0 0 0 1.462l1.178 1.101a1 1 0 0 1 .317.764l-.055 1.612a1 1 0 0 0 1.034 1.033l1.611-.054a1 1 0 0 1 .764.316l1.101 1.178a1 1 0 0 0 1.462 0l1.1-1.178a1 1 0 0 1 .765-.316l1.611.054a1 1 0 0 0 1.033-1.033l-.054-1.612a1 1 0 0 1 .317-.764l1.178-1.1a1 1 0 0 0 0-1.462L13.47 6.13a1 1 0 0 1-.317-.764l.054-1.612a1 1 0 0 0-1.033-1.033l-1.611.054a1 1 0 0 1-.765-.316l-1.1-1.178Zm3.032 5.115L10.6 5.264 6.9 8.963 5.335 7.396l-1.13 1.13L6.9 11.225l4.83-4.83Z"
      fill="#F4F6F8"
    />
  </svg>
))
SvgActionVerified.displayName = 'SvgActionVerified'
const Memo = memo(SvgActionVerified)
export { Memo as SvgActionVerified }
