// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgActionReplay = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" ref={ref} {...props}>
    <path d="M5 8a3 3 0 1 1 1.5 2.6l-1 1.73A5 5 0 1 0 3 8H1l3 4 3-4H5Z" fill="#F4F6F8" />
  </svg>
))
SvgActionReplay.displayName = 'SvgActionReplay'
const Memo = memo(SvgActionReplay)
export { Memo as SvgActionReplay }
