// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgActionShare = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg width={17} height={16} viewBox="0 0 17 16" fill="none" xmlns="http://www.w3.org/2000/svg" ref={ref} {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="m15.06 8-7-5v3H6.708c-3.65 0-5.65 2-5.65 4v2h2v-1c0-.552.445-1 .997-1H8.06v3l7-5Z"
      fill="#F4F6F8"
    />
  </svg>
))
SvgActionShare.displayName = 'SvgActionShare'
const Memo = memo(SvgActionShare)
export { Memo as SvgActionShare }
