// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgActionPayment = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" ref={ref} {...props}>
    <path
      d="M5 9a4 4 0 1 0 0-8 4 4 0 0 0 0 8ZM12.707 1h-2v10.619l-1.37-1.326-1.415 1.414 3.785 3.707 3.707-3.707L14 10.293l-1.293 1.293V1Z"
      fill="#F4F6F8"
    />
  </svg>
))
SvgActionPayment.displayName = 'SvgActionPayment'
const Memo = memo(SvgActionPayment)
export { Memo as SvgActionPayment }
