// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgCategoriesGaming = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" ref={ref} {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M11 3h2v2h-2V3ZM4.5 9.576A3 3 0 0 1 7.47 7h.116l1.707 1.707.293.293H14.414l.293-.293L16.414 7h.117a3 3 0 0 1 2.97 2.576l1.123 7.86a1.37 1.37 0 0 1-2.495.954l-1.297-1.945-.297-.445h-9.07l-.297.445L5.87 18.39a1.37 1.37 0 0 1-2.495-.953L4.5 9.576ZM7.47 5a5 5 0 0 0-4.95 4.293l-1.124 7.861a3.37 3.37 0 0 0 6.14 2.346l1-1.5h6.929l1 1.5a3.37 3.37 0 0 0 6.139-2.346L21.48 9.293A5 5 0 0 0 16.53 5H15.586l-.293.293L13.586 7h-3.172L8.707 5.293 8.414 5H7.47ZM8 10H6v2h2v-2Zm10 0h-2v2h2v-2Z"
      fill="#F4F6F8"
    />
  </svg>
))
SvgCategoriesGaming.displayName = 'SvgCategoriesGaming'
const Memo = memo(SvgCategoriesGaming)
export { Memo as SvgCategoriesGaming }
