// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgCategoriesPeopleAndBlogs = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" ref={ref} {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M15 20v2h2v-2a2 2 0 0 0-2-2H9a2 2 0 0 0-2 2v2h2v-2h6ZM5 18H3V6h18v12h-2v2h2a2 2 0 0 0 2-2V6a2 2 0 0 0-2-2H3a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h2v-2Zm5-6a2 2 0 1 1 4 0 2 2 0 0 1-4 0Zm2-4a4 4 0 1 0 0 8 4 4 0 0 0 0-8Z"
      fill="#F4F6F8"
    />
  </svg>
))
SvgCategoriesPeopleAndBlogs.displayName = 'SvgCategoriesPeopleAndBlogs'
const Memo = memo(SvgCategoriesPeopleAndBlogs)
export { Memo as SvgCategoriesPeopleAndBlogs }
