// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgControlsSeekBackward5 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" ref={ref} {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M12 4a8 8 0 0 0-8 8H2C2 6.477 6.477 2 12 2v2Zm4 5-4 3 4 3V9Zm-5 0-4 3 4 3V9Z"
      fill="#F4F6F8"
    />
  </svg>
))
SvgControlsSeekBackward5.displayName = 'SvgControlsSeekBackward5'
const Memo = memo(SvgControlsSeekBackward5)
export { Memo as SvgControlsSeekBackward5 }
