// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgControlsSearch = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" ref={ref} {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M10 1a9 9 0 1 0 0 18 9 9 0 0 0 0-18Zm-7 9a7 7 0 1 1 14 0 7 7 0 0 1-14 0Z"
      fill="#F4F6F8"
    />
    <path d="m22.707 21.293-4-4-1.414 1.414 4 4 1.414-1.414Z" fill="#F4F6F8" />
  </svg>
))
SvgControlsSearch.displayName = 'SvgControlsSearch'
const Memo = memo(SvgControlsSearch)
export { Memo as SvgControlsSearch }
