// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgControlsZoomOut = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" ref={ref} {...props}>
    <path d="M14 11V9H6v2h8Z" fill="#F4F6F8" />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M1 10a9 9 0 1 1 18 0 9 9 0 0 1-18 0Zm9-7a7 7 0 1 0 0 14 7 7 0 0 0 0-14Z"
      fill="#F4F6F8"
    />
    <path d="m18.707 17.293 4 4-1.414 1.414-4-4 1.414-1.414Z" fill="#F4F6F8" />
  </svg>
))
SvgControlsZoomOut.displayName = 'SvgControlsZoomOut'
const Memo = memo(SvgControlsZoomOut)
export { Memo as SvgControlsZoomOut }
