// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgControlsNext = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" ref={ref} {...props}>
    <path fillRule="evenodd" clipRule="evenodd" d="M18 19V5h2v14h-2Z" fill="#F4F6F8" />
    <path d="m4 5 11 7-11 7V5Z" fill="#F4F6F8" />
  </svg>
))
SvgControlsNext.displayName = 'SvgControlsNext'
const Memo = memo(SvgControlsNext)
export { Memo as SvgControlsNext }
