// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgControlsSeekForward10 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" ref={ref} {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M12 4a8 8 0 1 1 0 16v2c5.523 0 10-4.477 10-10S17.523 2 12 2v2ZM8 9l4 3-4 3V9Zm5 0 4 3-4 3V9Z"
      fill="#F4F6F8"
    />
  </svg>
))
SvgControlsSeekForward10.displayName = 'SvgControlsSeekForward10'
const Memo = memo(SvgControlsSeekForward10)
export { Memo as SvgControlsSeekForward10 }
