// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgControlsPipOn = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" ref={ref} {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M3 3a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h18a2 2 0 0 0 2-2V5a2 2 0 0 0-2-2H3Zm0 2h18v14H3V5Zm16 8h-6v4h6v-4Z"
      fill="#F4F6F8"
    />
  </svg>
))
SvgControlsPipOn.displayName = 'SvgControlsPipOn'
const Memo = memo(SvgControlsPipOn)
export { Memo as SvgControlsPipOn }
