// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgHeading = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" ref={ref} {...props}>
    <path d="M5 2H3v12h2V9h6v5h2V2h-2v5H5V2Z" fill="#F4F6F8" />
  </svg>
))
SvgHeading.displayName = 'SvgHeading'
const Memo = memo(SvgHeading)
export { Memo as SvgHeading }
