// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgIconRankBronze = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    width={192}
    height={192}
    viewBox="0 0 192 192"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    ref={ref}
    {...props}
  >
    <g clipPath="url(#clip0_2633_1237)">
      <path d="M96 167.974C56.72 166.931 25.07 135.28 24.027 96H96v71.974Z" fill="#fff" />
    </g>
    <g clipPath="url(#clip1_2633_1237)">
      <path d="M167.974 96C166.931 135.28 135.28 166.93 96 167.973V96h71.974Z" fill="#fff" />
    </g>
    <path d="M96 96H24V24h72v72Z" fill="#fff" />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M168 90.36V96h-5.64L96 29.64V24h5.64L168 90.36ZM96 41.28v11.255L139.466 96h11.254L96 41.28Zm0 33.64V63.6L128.4 96h-11.32L96 74.92ZM96 96h10.08L96 85.92V96Zm17.28-72h11.254L168 67.466V78.72L113.28 24Zm33.64 0H135.6L168 56.4V45.08L146.92 24ZM168 34.08 157.92 24H168v10.08Z"
      fill="#fff"
    />
    <defs>
      <clipPath id="clip0_2633_1237">
        <path fill="#fff" transform="rotate(-180 48 84)" d="M0 0h72v72H0z" />
      </clipPath>
      <clipPath id="clip1_2633_1237">
        <path fill="#fff" transform="rotate(90 36 132)" d="M0 0h72v72H0z" />
      </clipPath>
    </defs>
  </svg>
))
SvgIconRankBronze.displayName = 'SvgIconRankBronze'
const Memo = memo(SvgIconRankBronze)
export { Memo as SvgIconRankBronze }
