// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgIconRankDiamond = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    width={192}
    height={192}
    viewBox="0 0 192 192"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    ref={ref}
    {...props}
  >
    <g clipPath="url(#clip0_2633_1240)" fill="#fff">
      <path d="M24 96.026v8.004c34.861 1.037 62.933 29.109 63.97 63.97h8.004C94.93 128.72 63.28 97.069 24 96.026Z" />
      <path d="M79.966 168C78.935 137.557 54.443 113.065 24 112.034v8.005c26.024 1.024 46.937 21.937 47.96 47.961h8.006Z" />
      <path d="M64 168c0-22.091-17.909-40-40-40v8c17.673 0 32 14.327 32 32h8Z" />
      <path d="M48 168c0-13.255-10.745-24-24-24v8c8.837 0 16 7.163 16 16h8ZM32 168a8 8 0 0 0-8-8v8h8Z" />
    </g>
    <g clipPath="url(#clip1_2633_1240)" fill="#fff">
      <path d="M96.026 168h8.004c1.037-34.861 29.109-62.933 63.97-63.97v-8.004C128.72 97.07 97.069 128.72 96.026 168Z" />
      <path d="M168 112.034c-30.443 1.031-54.935 25.523-55.966 55.966h8.005c1.024-26.024 21.937-46.937 47.961-47.961v-8.005Z" />
      <path d="M168 128c-22.091 0-40 17.909-40 40h8c0-17.673 14.327-32 32-32v-8Z" />
      <path d="M168 144c-13.255 0-24 10.745-24 24h8c0-8.837 7.163-16 16-16v-8ZM168 160a8 8 0 0 0-8 8h8v-8Z" />
    </g>
    <g clipPath="url(#clip2_2633_1240)" fill="#fff">
      <path d="M95.974 24H87.97C86.933 58.861 58.861 86.933 24 87.97v8.004C63.28 94.93 94.931 63.28 95.974 24Z" />
      <path d="M24 79.966C54.443 78.935 78.935 54.443 79.966 24h-8.005C70.937 50.024 50.024 70.937 24 71.96v8.006Z" />
      <path d="M24 64c22.091 0 40-17.909 40-40h-8c0 17.673-14.327 32-32 32v8Z" />
      <path d="M24 48c13.255 0 24-10.745 24-24h-8c0 8.837-7.163 16-16 16v8ZM24 32a8 8 0 0 0 8-8h-8v8Z" />
    </g>
    <g clipPath="url(#clip3_2633_1240)" fill="#fff">
      <path d="M168 95.974V87.97c-34.861-1.037-62.933-29.109-63.97-63.97h-8.004C97.07 63.28 128.72 94.931 168 95.974Z" />
      <path d="M112.034 24c1.031 30.443 25.523 54.935 55.966 55.966v-8.005C141.976 70.937 121.063 50.024 120.039 24h-8.005Z" />
      <path d="M128 24c0 22.091 17.909 40 40 40v-8c-17.673 0-32-14.327-32-32h-8Z" />
      <path d="M144 24c0 13.255 10.745 24 24 24v-8c-8.837 0-16-7.163-16-16h-8ZM160 24a8 8 0 0 0 8 8v-8h-8Z" />
    </g>
    <defs>
      <clipPath id="clip0_2633_1240">
        <path fill="#fff" transform="translate(24 96)" d="M0 0h72v72H0z" />
      </clipPath>
      <clipPath id="clip1_2633_1240">
        <path fill="#fff" transform="rotate(-90 132 36)" d="M0 0h72v72H0z" />
      </clipPath>
      <clipPath id="clip2_2633_1240">
        <path fill="#fff" transform="rotate(90 36 60)" d="M0 0h72v72H0z" />
      </clipPath>
      <clipPath id="clip3_2633_1240">
        <path fill="#fff" transform="rotate(-180 84 48)" d="M0 0h72v72H0z" />
      </clipPath>
    </defs>
  </svg>
))
SvgIconRankDiamond.displayName = 'SvgIconRankDiamond'
const Memo = memo(SvgIconRankDiamond)
export { Memo as SvgIconRankDiamond }
