// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgIconRankSilver = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    width={192}
    height={192}
    viewBox="0 0 192 192"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    ref={ref}
    {...props}
  >
    <g clipPath="url(#clip0_2633_1238)" fill="#fff">
      <path d="M32 96v72h-8V96h8ZM96 96v72h-8V96h8ZM80 168V96h-8v72h8ZM48 96v72h-8V96h8ZM64 168V96h-8v72h8Z" />
    </g>
    <g clipPath="url(#clip1_2633_1238)" fill="#fff">
      <path d="M96 160h72v8H96v-8ZM96 96h72v8H96v-8ZM168 112H96v8h72v-8ZM96 144h72v8H96v-8ZM168 128H96v8h72v-8Z" />
    </g>
    <path d="M96 24v72H24V24h72ZM168 96H96V24h72v72Z" fill="#fff" />
    <defs>
      <clipPath id="clip0_2633_1238">
        <path fill="#fff" transform="rotate(-90 96 72)" d="M0 0h72v72H0z" />
      </clipPath>
      <clipPath id="clip1_2633_1238">
        <path fill="#fff" transform="rotate(180 84 84)" d="M0 0h72v72H0z" />
      </clipPath>
    </defs>
  </svg>
))
SvgIconRankSilver.displayName = 'SvgIconRankSilver'
const Memo = memo(SvgIconRankSilver)
export { Memo as SvgIconRankSilver }
