// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgIllustrativeTrash = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg width={48} height={48} viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg" ref={ref} {...props}>
    <path d="M13.074 17h21.852l-1.857 26H14.93l-1.857-26Z" stroke="#F4F6F8" strokeWidth={2} />
    <mask id="path-2-inside-1_1767_4359" fill="#fff">
      <rect x={9} y={12} width={30} height={6} rx={1} />
    </mask>
    <rect
      x={9}
      y={12}
      width={30}
      height={6}
      rx={1}
      stroke="#F4F6F8"
      strokeWidth={4}
      mask="url(#path-2-inside-1_1767_4359)"
    />
    <mask id="path-3-inside-2_1767_4359" fill="#fff">
      <rect x={18} y={8} width={12} height={6} rx={1} />
    </mask>
    <rect
      x={18}
      y={8}
      width={12}
      height={6}
      rx={1}
      stroke="#F4F6F8"
      strokeWidth={4}
      mask="url(#path-3-inside-2_1767_4359)"
    />
    <path d="M24 39V21M28.5 39 30 21M19.5 39 18 21" stroke="#fff" strokeWidth={2} strokeLinecap="round" />
  </svg>
))
SvgIllustrativeTrash.displayName = 'SvgIllustrativeTrash'
const Memo = memo(SvgIllustrativeTrash)
export { Memo as SvgIllustrativeTrash }
