// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgJoyTokenMonochrome48 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg width={48} height={48} viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg" ref={ref} {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M24 44c11.046 0 20-8.954 20-20S35.046 4 24 4 4 12.954 4 24s8.954 20 20 20Zm-.008-12a8 8 0 0 1-8-8h-6c0 7.732 6.268 14 14 14s14-6.268 14-14h-6a8 8 0 0 1-8 8Z"
      fill="#F4F6F8"
    />
  </svg>
))
SvgJoyTokenMonochrome48.displayName = 'SvgJoyTokenMonochrome48'
const Memo = memo(SvgJoyTokenMonochrome48)
export { Memo as SvgJoyTokenMonochrome48 }
