// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgLoaderMStatic = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg width={32} height={32} viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg" ref={ref} {...props}>
    <g clipPath="url(#clip0_2645_501)">
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M32 3.556H0V0h32v3.556ZM17.778 32H0v-3.556h17.778V32ZM0 24.889h21.333v-3.556H0v3.556Zm28.444-14.222H0V7.11h28.444v3.556ZM0 17.777h24.889v-3.555H0v3.556Z"
        fill="#52616B"
      />
    </g>
    <defs>
      <clipPath id="clip0_2645_501">
        <path fill="#fff" d="M0 0h32v32H0z" />
      </clipPath>
    </defs>
  </svg>
))
SvgLoaderMStatic.displayName = 'SvgLoaderMStatic'
const Memo = memo(SvgLoaderMStatic)
export { Memo as SvgLoaderMStatic }
