// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgLogoDiscordOnLight = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg width={24} height={25} viewBox="0 0 24 25" fill="none" xmlns="http://www.w3.org/2000/svg" ref={ref} {...props}>
    <path
      d="M18.956 5.703a16.495 16.495 0 0 0-4.134-1.273c-.182.313-.384.738-.526 1.071a15.802 15.802 0 0 0-4.58 0 13.146 13.146 0 0 0-.525-1.071c-1.455.242-2.84.677-4.135 1.273-2.617 3.861-3.325 7.631-2.971 11.35A16.848 16.848 0 0 0 7.15 19.59c.404-.545.768-1.132 1.081-1.748a10.604 10.604 0 0 1-1.708-.819 6.46 6.46 0 0 0 .414-.323c3.295 1.506 6.864 1.506 10.118 0 .142.111.273.222.415.323-.546.324-1.112.597-1.708.819.313.616.677 1.203 1.081 1.748a16.755 16.755 0 0 0 5.065-2.537c.434-4.305-.688-8.045-2.952-11.35ZM8.686 14.76c-.99 0-1.8-.9-1.8-2 0-1.103.79-2.002 1.8-2.002 1 0 1.819.9 1.799 2.001 0 1.102-.799 2.001-1.8 2.001Zm6.641 0c-.99 0-1.8-.9-1.8-2 0-1.103.79-2.002 1.8-2.002 1 0 1.82.9 1.8 2.001 0 1.102-.79 2.001-1.8 2.001Z"
      fill="#5865F2"
    />
  </svg>
))
SvgLogoDiscordOnLight.displayName = 'SvgLogoDiscordOnLight'
const Memo = memo(SvgLogoDiscordOnLight)
export { Memo as SvgLogoDiscordOnLight }
