// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgLogoVkMonochrome = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg width={24} height={25} viewBox="0 0 24 25" fill="none" xmlns="http://www.w3.org/2000/svg" ref={ref} {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M14.76 3.005H9.24C4.2 3.005 3 4.205 3 9.245v5.52c0 5.04 1.2 6.24 6.24 6.24h5.52c5.04 0 6.24-1.2 6.24-6.24v-5.52c0-5.04-1.2-6.24-6.24-6.24Zm2.584 5.72c.397 0 .48.204.397.482-.167.765-1.766 3.017-1.766 3.017-.14.223-.195.334 0 .584.068.096.215.24.382.403.172.17.367.36.522.543.563.634.988 1.17 1.107 1.538.108.37-.08.558-.455.558H16.22c-.352 0-.529-.197-.911-.623-.162-.18-.361-.402-.626-.667-.78-.75-1.113-.848-1.308-.848-.264 0-.343.075-.343.45v1.177c0 .323-.103.51-.937.51-1.39 0-2.919-.844-4.003-2.401-1.627-2.28-2.072-4.005-2.072-4.352 0-.195.075-.371.45-.371H7.78c.336 0 .462.146.588.51.642 1.87 1.724 3.504 2.169 3.504.167 0 .243-.077.243-.5v-1.934c-.03-.55-.222-.788-.364-.964-.088-.109-.157-.194-.157-.315 0-.147.125-.301.334-.301h2.062c.278 0 .375.148.375.482v2.6c0 .278.121.376.204.376.167 0 .306-.098.612-.404.946-1.056 1.613-2.683 1.613-2.683.084-.195.237-.371.571-.371h1.313Z"
      fill="#fff"
    />
  </svg>
))
SvgLogoVkMonochrome.displayName = 'SvgLogoVkMonochrome'
const Memo = memo(SvgLogoVkMonochrome)
export { Memo as SvgLogoVkMonochrome }
