// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgSidebarReferrals = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg width={22} height={18} viewBox="0 0 22 18" fill="none" xmlns="http://www.w3.org/2000/svg" ref={ref} {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M15 0a4 4 0 1 0 0 8 4 4 0 0 0 0-8Zm-2 4a2 2 0 1 1 4 0 2 2 0 0 1-4 0Z"
      fill="#F4F6F8"
    />
    <path
      d="M5 2a2 2 0 1 0 0 4 2 2 0 0 0 0-4ZM11.5 16H20v-1a3 3 0 0 0-3-3h-4a3 3 0 0 0-3 3v1.5H8V15c0-.342.034-.677.1-1H4v-2h3.991A2.2 2.2 0 0 0 5.8 10H4a2 2 0 0 0-2 2v2H0v-2a4 4 0 0 1 4-4h1.8a4.202 4.202 0 0 1 4.057 3.11A4.98 4.98 0 0 1 13 10h4a5 5 0 0 1 5 5v1a2 2 0 0 1-2 2h-8.5v-2Z"
      fill="#F4F6F8"
    />
  </svg>
))
SvgSidebarReferrals.displayName = 'SvgSidebarReferrals'
const Memo = memo(SvgSidebarReferrals)
export { Memo as SvgSidebarReferrals }
