// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgSidebarHome = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" ref={ref} {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M10 21.002A1.999 1.999 0 0 1 8 23H3a2 2 0 0 1-2-2v-9.555a2 2 0 0 1 .662-1.486L12 .655l10.338 9.304A2 2 0 0 1 23 11.445V21a2 2 0 0 1-2 2h-5a2 2 0 0 1-2-2v-2h2v2h5v-9.555l-9-8.1-9 8.1V21h5v-4a2 2 0 0 1 2-2h6v2h-6v4.002Z"
      fill="#F4F6F8"
    />
  </svg>
))
SvgSidebarHome.displayName = 'SvgSidebarHome'
const Memo = memo(SvgSidebarHome)
export { Memo as SvgSidebarHome }
