// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgSidebarMarketplace = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" ref={ref} {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M8 5a4 4 0 1 1 8 0v1h3.5a2 2 0 0 1 1.987 1.77l1.5 13A2 2 0 0 1 21 23H3a2 2 0 0 1-1.987-2.23L2.256 10h2.013L3 21h18L19.5 8H2.487l.026-.23A2 2 0 0 1 4.5 6H8V5Zm2 1h4V5a2 2 0 1 0-4 0v1Z"
      fill="#F4F6F8"
    />
    <path d="m10 11 5 3.5-5 3.5v-7Z" fill="#F4F6F8" />
  </svg>
))
SvgSidebarMarketplace.displayName = 'SvgSidebarMarketplace'
const Memo = memo(SvgSidebarMarketplace)
export { Memo as SvgSidebarMarketplace }
