// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgTierIcon4 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg width={36} height={36} viewBox="0 0 36 36" fill="none" xmlns="http://www.w3.org/2000/svg" ref={ref} {...props}>
    <path d="M0 18h18v18H0V18Z" fill="#33DEE9" />
    <g clipPath="url(#clip0_4782_70855)" fill="#33DEE9">
      <path d="M18 2H0V0h18v2ZM18 18H0v-2h18v2ZM0 14h18v-2H0v2ZM18 6H0V4h18v2ZM0 10h18V8H0v2Z" />
    </g>
    <path
      d="M36 18H18V0h18v18ZM36 18v2h-2v-2h2ZM26 24v-2h2v2h-2ZM26 26h2v2h-2v-2ZM24 26h2v-2h-2v-2h-2v2h2v2ZM24 28h-2v-2h2v2ZM24 30v-2h2v2h-2ZM28 30v2h-2v-2h2ZM30 30v2h2v-2h-2ZM30 30h-2v-2h2v2ZM24 30h-2v2h2v-2Z"
      fill="#33DEE9"
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M34 22v-2h-2v-2h-2v2h-2v-2h-2v2h-2v-2h-2v2h-2v-2h-2v2h2v2h-2v2h2v2h-2v2h2v2h-2v2h2v2h-2v2h2v-2h2v2h2v-2h2v2h2v-2h2v2h2v-2h2v2h2v-2h-2v-2h2v-2h-2v-2h2v-2h-2v-2h2v-2h-2Zm-2 0h2v2h-2v-2Zm-2 0h2v-2h-2v2Zm0 2h2v2h-2v-2Zm-2 0h2v-2h-2v-2h-2v2h-2v-2h-2v2h-2v2h2v2h-2v2h2v2h-2v2h2v2h2v-2h2v2h2v-2h2v2h2v-2h2v-2h-2v-2h2v-2h-2v2h-2v-2h-2v-2Z"
      fill="#33DEE9"
    />
    <defs>
      <clipPath id="clip0_4782_70855">
        <path fill="#fff" d="M0 0h18v18H0z" />
      </clipPath>
    </defs>
  </svg>
))
SvgTierIcon4.displayName = 'SvgTierIcon4'
const Memo = memo(SvgTierIcon4)
export { Memo as SvgTierIcon4 }
