// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgTierIcon1 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg width={36} height={36} viewBox="0 0 36 36" fill="none" xmlns="http://www.w3.org/2000/svg" ref={ref} {...props}>
    <g clipPath="url(#clip0_1532_4284)" fill="#D92E61">
      <path d="M18 .007v2c8.715.26 15.733 7.278 15.993 15.993h2C35.733 8.18 27.82.267 18 .007Z" />
      <path d="M31.991 18C31.734 10.39 25.611 4.266 18 4.008V6.01c6.506.256 11.734 5.484 11.99 11.99h2.002Z" />
      <path d="M28 18c0-5.523-4.477-10-10-10v2a8 8 0 0 1 8 8h2Z" />
      <path d="M24 18a6 6 0 0 0-6-6v2a4 4 0 0 1 4 4h2ZM20 18a2 2 0 0 0-2-2v2h2Z" />
    </g>
    <g clipPath="url(#clip1_1532_4284)" fill="#D92E61">
      <path d="M36 20H18v-2h18v2ZM36 36H18v-2h18v2ZM18 32h18v-2H18v2ZM36 24H18v-2h18v2ZM18 28h18v-2H18v2Z" />
    </g>
    <path d="M18 36H0V18h18v18Z" fill="#D92E61" />
    <g clipPath="url(#clip2_1532_4284)" fill="#D92E61">
      <path d="M.007 18h2C2.267 9.285 9.285 2.267 18 2.007v-2C8.18.267.267 8.18.007 18Z" />
      <path d="M18 4.008C10.39 4.266 4.266 10.39 4.008 18H6.01C6.266 11.494 11.494 6.266 18 6.01V4.008Z" />
      <path d="M18 8C12.477 8 8 12.477 8 18h2a8 8 0 0 1 8-8V8Z" />
      <path d="M18 12a6 6 0 0 0-6 6h2a4 4 0 0 1 4-4v-2ZM18 16a2 2 0 0 0-2 2h2v-2Z" />
    </g>
    <defs>
      <clipPath id="clip0_1532_4284">
        <path fill="#fff" transform="translate(18)" d="M0 0h18v18H0z" />
      </clipPath>
      <clipPath id="clip1_1532_4284">
        <path fill="#fff" transform="translate(18 18)" d="M0 0h18v18H0z" />
      </clipPath>
      <clipPath id="clip2_1532_4284">
        <path fill="#fff" transform="rotate(-90 9 9)" d="M0 0h18v18H0z" />
      </clipPath>
    </defs>
  </svg>
))
SvgTierIcon1.displayName = 'SvgTierIcon1'
const Memo = memo(SvgTierIcon1)
export { Memo as SvgTierIcon1 }
