// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgUnorderedList = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" ref={ref} {...props}>
    <path
      d="M2 4a1 1 0 1 0 0-2 1 1 0 0 0 0 2ZM5 4h10V2H5v2ZM15 9V7H5v2h10ZM5 12h10v2H5v-2ZM3 8a1 1 0 1 1-2 0 1 1 0 0 1 2 0ZM2 14a1 1 0 1 0 0-2 1 1 0 0 0 0 2Z"
      fill="#F4F6F8"
    />
  </svg>
))
SvgUnorderedList.displayName = 'SvgUnorderedList'
const Memo = memo(SvgUnorderedList)
export { Memo as SvgUnorderedList }
