// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgGlyphChevronLeft = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M6.414 8l5.293 5.293-1.414 1.414L3.586 8l6.707-6.707 1.414 1.414L6.414 8z"
      fill="#F4F6F8"
    />
  </svg>
)
