// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgNavVideos = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M10 11l5 3-5 3v-6z" fill="#F4F6F8" />
    <path d="M18 2H6" stroke="#F4F6F8" strokeWidth={2} strokeMiterlimit={10} strokeLinecap="square" />
    <path d="M10 11l5 3-5 3v-6z" fill="#F4F6F8" />
    <rect
      x={2}
      y={6}
      width={20}
      height={16}
      rx={1}
      stroke="#F4F6F8"
      strokeWidth={2}
      strokeMiterlimit={10}
      strokeLinecap="square"
    />
  </svg>
)
