// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgPlayerReplay = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M8 11l-3 4-3-4h6z" fill="#F4F6F8" />
    <path d="M5 12a7 7 0 112 4.899" stroke="#F4F6F8" strokeWidth={2} />
  </svg>
)
