// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgPlayerPlaylistAdd = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M15 12H2M15 8H2M12 16H2M22 16h-8M18 12v8" stroke="#F4F6F8" strokeWidth={2} strokeMiterlimit={10} />
  </svg>
)
