// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgActionHeartSolid = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M2.007 3.347a4 4 0 015.646-.34L8 3.314l.346-.307a4 4 0 015.308 5.986L8.001 14 2.347 8.993a4 4 0 01-.34-5.646z"
      fill="#F4F6F8"
    />
  </svg>
)
