// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgActionExclamation = React.memo((props: React.SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M8 14A6 6 0 108 2a6 6 0 000 12zm1-4v2H7v-2h2zm0-6v5H7V4h2z"
      fill="#F4F6F8"
    />
  </svg>
))
SvgActionExclamation.displayName = 'SvgActionExclamation'
