// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgActionHeartOutline = React.memo((props: React.SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      d="M8 4.65l-.663-.588-.347-.307a3 3 0 00-3.98 4.49s0 0 0 0 0 0 0 0l4.991 4.42 4.99-4.42L8 4.65zm0 0l.664-.588M8 4.651l.664-.589m0 0l.345-.306m-.345.306l.345-.306m0 0a3 3 0 014.236.253m-4.236-.253l4.236.253m0 0a3 3 0 01-.254 4.235l.254-4.235z"
      stroke="#F4F6F8"
      strokeWidth={2}
      strokeLinecap="round"
    />
  </svg>
))
SvgActionHeartOutline.displayName = 'SvgActionHeartOutline'
