// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgActionMenu = React.memo((props: React.SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M2 13h12v-2H2v2zm0-4h12V7H2v2zm0-6v2h12V3H2z" fill="#F4F6F8" />
  </svg>
))
SvgActionMenu.displayName = 'SvgActionMenu'
