// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgActionSoundOn = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      d="M3 6l2-4h2v12H5l-2-4H2a1 1 0 01-1-1V7a1 1 0 011-1h1zM13 8a4 4 0 00-4-4V2a6 6 0 010 12v-2a4 4 0 004-4z"
      fill="#F4F6F8"
    />
    <path d="M11 8a2 2 0 00-2-2v4a2 2 0 002-2z" fill="#F4F6F8" />
  </svg>
)
