// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgActionShow = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M8 13c5 0 7-5 7-5s-2-5-7-5-7 5-7 5 2 5 7 5zm0-3a2 2 0 100-4 2 2 0 000 4z"
      fill="#F4F6F8"
    />
  </svg>
)
