// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgActionLinkUrl = React.memo((props: React.SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      d="M13 6c0-.375-.149-.735-.414-1L11 3.414a1.414 1.414 0 00-2 0l-.293.293-1.414-1.414L7.586 2a3.414 3.414 0 014.828 0L14 3.586a3.414 3.414 0 010 4.828l-.293.293-1.414-1.414.293-.293c.265-.265.414-.625.414-1zM7.707 6.293l-4-4-1.414 1.414 4 4 1.414-1.414zM3.414 11a1.414 1.414 0 010-2l.293-.293-1.414-1.414L2 7.586a3.414 3.414 0 000 4.828L3.586 14a3.414 3.414 0 004.828 0l.293-.293-1.414-1.414-.293.293a1.414 1.414 0 01-2 0L3.414 11zM13.707 12.293l-4-4-1.414 1.414 4 4 1.414-1.414z"
      fill="#F4F6F8"
    />
  </svg>
))
SvgActionLinkUrl.displayName = 'SvgActionLinkUrl'
