// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgActionNewTab = React.memo((props: React.SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M3 2a1 1 0 00-1 1v10a1 1 0 001 1h10a1 1 0 001-1V3a1 1 0 00-1-1H3zm9 7h-2V7.414l-3.293 3.293-1.414-1.414L8.586 6H7V4h5v5z"
      fill="#F4F6F8"
    />
  </svg>
))
SvgActionNewTab.displayName = 'SvgActionNewTab'
