// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgActionSwitchMember = React.memo((props: React.SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M5 8a4 4 0 00-4 4v1a1 1 0 001 1h6v-2H5V8zM11.586 9L9.293 6.707l1.414-1.414L14.414 9l-3.707 3.707-1.414-1.414L11.586 9z"
      fill="#F4F6F8"
    />
    <path d="M7 10V8h5v2H7zM8 4a2 2 0 11-4 0 2 2 0 014 0z" fill="#F4F6F8" />
  </svg>
))
SvgActionSwitchMember.displayName = 'SvgActionSwitchMember'
