// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgActionWarning = React.memo((props: React.SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M8.857 2.486a1 1 0 00-1.714 0l-6 10A1 1 0 002 14h12a1 1 0 00.857-1.514l-6-10zM9 10V5H7v5h2zm0 3v-2H7v2h2z"
      fill="#fff"
    />
  </svg>
))
SvgActionWarning.displayName = 'SvgActionWarning'
