// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgActionChannel = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      d="M8 6a2 2 0 100-4 2 2 0 000 4zM3 13v.143c0 .473.384.857.857.857h8.286a.857.857 0 00.857-.857V13a5 5 0 00-10 0z"
      fill="#F4F6F8"
    />
  </svg>
)
