// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgActionDraft = React.memo((props: React.SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      d="M3 3a1 1 0 011-1h3a1 1 0 011 1v4a1 1 0 001 1h3a1 1 0 011 1v4a1 1 0 01-1 1H4a1 1 0 01-1-1V3z"
      fill="#F4F6F8"
    />
    <path d="M11 6h2l-3-4v3a1 1 0 001 1z" fill="#F4F6F8" />
  </svg>
))
SvgActionDraft.displayName = 'SvgActionDraft'
