// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgActionSoundOff = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={14} height={14} viewBox="0 0 14 14" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      d="M12.445 11.03l1.262 1.263-1.414 1.414-12-12L1.707.293l1.764 1.764L4 1h2v3.586l2 2V5a2 2 0 011.606 3.192l1.422 1.422A4 4 0 008 3V1a6 6 0 014.445 10.03zM6 9.914L1.086 5H1a1 1 0 00-1 1v2a1 1 0 001 1h1l2 4h2V9.914z"
      fill="#F4F6F8"
    />
  </svg>
)
