// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgActionNewChannel = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      d="M6 6a2 2 0 100-4 2 2 0 000 4zM12 5v3h3v2h-3v3h-2v-3H7V8h3V5h2zM1 12a4 4 0 014-4v4h3v2H2a1 1 0 01-1-1v-1z"
      fill="#F4F6F8"
    />
  </svg>
)
