// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgActionNotifications = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      d="M8.966 1H5.494L4 8.106h2.58L5.978 15 12.6 4.784H9.053l.676-2.75a.898.898 0 00-.152-.716A.762.762 0 008.966 1z"
      fill="#F4F6F8"
    />
  </svg>
)
