// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgActionZoomIn = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M12.89 11.476a6 6 0 10-1.414 1.414l1.817 1.817 1.414-1.414-1.816-1.816zM4 9h3v3h2V9h3V7H9V4H7v3H4v2z"
      fill="#F4F6F8"
    />
  </svg>
)
