// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgActionAuction = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      d="M6.709 2.389c.233-.445.431-.91.591-1.389l4.2 4.2a9.376 9.376 0 00-2.547 1.31l5.326 4.734a2.15 2.15 0 11-3.034 3.035L6.51 8.953A9.376 9.376 0 005.2 11.5L1 7.3a9.376 9.376 0 003.665-2.265l.37-.37A9.377 9.377 0 006.709 2.39z"
      fill="#F4F6F8"
    />
  </svg>
)
