// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgActionSearch = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M11.476 12.89a6 6 0 111.414-1.414l1.817 1.817-1.414 1.414-1.816-1.816zM12 8a4 4 0 11-8 0 4 4 0 018 0z"
      fill="#F4F6F8"
    />
  </svg>
)
