// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgActionMint = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      d="M8 1H7v4H2v2a2 2 0 012 2v1h7.6A2.4 2.4 0 0014 7.6V7a6 6 0 00-6-6zM6 15a2 2 0 100-4 2 2 0 000 4zM12 15a2 2 0 100-4 2 2 0 000 4z"
      fill="#F4F6F8"
    />
  </svg>
)
