// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgActionChevronT = React.memo((props: React.SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M8 6.414l-5.293 5.293-1.414-1.414L8 3.586l6.707 6.707-1.414 1.414L8 6.414z"
      fill="#F4F6F8"
    />
  </svg>
))
SvgActionChevronT.displayName = 'SvgActionChevronT'
