// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgActionVideoFile = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M2 3a1 1 0 011-1h10a1 1 0 011 1v1h-2v2h2v4h-2v2h2v1a1 1 0 01-1 1H3a1 1 0 01-1-1V3zm2 1h2v2H4V4zm2 6H4v2h2v-2zm2-6h2v2H8V4zm2 6H8v2h2v-2z"
      fill="#F4F6F8"
    />
  </svg>
)
