// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgActionUpload = React.memo((props: React.SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      d="M4.707 7.707L7 5.414V10h2V5.414l2.293 2.293 1.414-1.414L8 1.586 3.293 6.293l1.414 1.414zM2 12a2 2 0 002 2h8a2 2 0 002-2v-1h-2v1H4v-1H2v1z"
      fill="#F4F6F8"
    />
  </svg>
))
SvgActionUpload.displayName = 'SvgActionUpload'
