// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgActionEdit = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      d="M12.414 6.414l2-2-2.828-2.828-2 2 2.828 2.828zM10.414 8.414L4.828 14H2v-2.828l5.586-5.586 2.828 2.828z"
      fill="#F4F6F8"
    />
  </svg>
)
