// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgActionSoundOff = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      d="M13.445 12.03l1.262 1.263-1.414 1.414-12-12 1.414-1.414 1.764 1.764L5 2h2v3.586l2 2V6a2 2 0 011.606 3.192l1.422 1.422A4 4 0 009 4V2a6 6 0 014.445 10.03zM7 10.914L2.086 6H2a1 1 0 00-1 1v2a1 1 0 001 1h1l2 4h2v-3.086z"
      fill="#F4F6F8"
    />
  </svg>
)
