// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgActionAddVideo = React.memo((props: React.SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M0 3a1 1 0 011-1h10a1 1 0 011 1v4l3-3h1v8h-1l-3-3v4a1 1 0 01-1 1H1a1 1 0 01-1-1V3zm7 1H5v3H2v2h3v3h2V9h3V7H7V4z"
      fill="#F4F6F8"
    />
  </svg>
))
SvgActionAddVideo.displayName = 'SvgActionAddVideo'
