// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgActionNewDraftTab = React.memo((props: React.SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M15 3a2 2 0 00-2-2H3a2 2 0 00-2 2v10a2 2 0 002 2h2v-2H3V5h10v8h-2v2h2a2 2 0 002-2V3z" fill="#F4F6F8" />
    <path
      d="M5.707 11.707L7 10.414V15h2v-4.586l1.293 1.293 1.414-1.414L8 6.586l-3.707 3.707 1.414 1.414z"
      fill="#F4F6F8"
    />
  </svg>
))
SvgActionNewDraftTab.displayName = 'SvgActionNewDraftTab'
