// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgActionSell = React.memo((props: React.SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      d="M8.047 1l5.72 5.544c.15.144.233.34.233.544 0 .204-.084.4-.233.544L12.72 8.67 7.06 3H3.682V1h4.365z"
      fill="#F4F6F8"
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M6.23 5l5.545 5.544a.77.77 0 010 1.088l-3.143 3.143a.77.77 0 01-1.088 0L2 9.23V5h4.23zM3.88 7.947a.77.77 0 10.855-1.279.77.77 0 00-.855 1.28z"
      fill="#F4F6F8"
    />
  </svg>
))
SvgActionSell.displayName = 'SvgActionSell'
