// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgAlertsError32 = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={32} height={32} viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      d="M16 17.414l-4.293 4.293-1.414-1.414L14.586 16l-4.293-4.293 1.414-1.414L16 14.586l4.293-4.293 1.414 1.414L17.414 16l4.293 4.293-1.414 1.414L16 17.414z"
      fill="#FF695F"
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M0 16C0 7.163 7.163 0 16 0s16 7.163 16 16-7.163 16-16 16S0 24.837 0 16zM16 2C8.268 2 2 8.268 2 16s6.268 14 14 14 14-6.268 14-14S23.732 2 16 2z"
      fill="#FF695F"
    />
  </svg>
)
