// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgAlertsSuccess32 = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={32} height={32} viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M21.753 12.659l-1.506-1.318-6.296 7.196-2.244-2.244-1.414 1.414 3.756 3.756 7.704-8.805z" fill="#0EB152" />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M16 0C7.163 0 0 7.163 0 16s7.163 16 16 16 16-7.163 16-16S24.837 0 16 0zM2 16C2 8.268 8.268 2 16 2s14 6.268 14 14-6.268 14-14 14S2 23.732 2 16z"
      fill="#0EB152"
    />
  </svg>
)
