// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgAlertsLoader24 = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M12 4a8 8 0 100 16 8 8 0 000-16zM2 12C2 6.477 6.477 2 12 2s10 4.477 10 10-4.477 10-10 10S2 17.523 2 12z"
      fill="#B5C1C9"
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M4.652 18.783A9.973 9.973 0 0012 22c5.523 0 10-4.477 10-10S17.523 2 12 2v2A8 8 0 116.12 17.426l-1.47 1.357z"
      fill="#4038FF"
    />
  </svg>
)
