// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgControlsSoundLowVolume = React.memo((props: React.SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M10 4L6 9H3a1 1 0 00-1 1v4a1 1 0 001 1h3l4 5h2V4h-2zm4 6a2 2 0 110 4v2a4 4 0 000-8v2z"
      fill="#F4F6F8"
    />
  </svg>
))
SvgControlsSoundLowVolume.displayName = 'SvgControlsSoundLowVolume'
