// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgControlsFullScreen = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M5 15v4h4v2H5a2 2 0 01-2-2v-4h2zm16 0v4a2 2 0 01-2 2h-4v-2h4v-4h2zM3 9V5a2 2 0 012-2h4v2H5v4H3zm16 0V5h-4V3h4a2 2 0 012 2v4h-2z"
      fill="#F4F6F8"
    />
  </svg>
)
