// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgControlsNext = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path fillRule="evenodd" clipRule="evenodd" d="M18 19V5h2v14h-2z" fill="#F4F6F8" />
    <path d="M4 5l11 7-11 7V5z" fill="#F4F6F8" />
  </svg>
)
