// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgControlsPlaylist = React.memo((props: React.SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M2 7h16v2H2V7zM18 11H2v2h16v-2zM22 18l-5-3v6l5-3zM15 15H2v2h13v-2z" fill="#F4F6F8" />
  </svg>
))
SvgControlsPlaylist.displayName = 'SvgControlsPlaylist'
