// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgControlsZoomIn = React.memo((props: React.SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M11 9h3v2h-3v3H9v-3H6V9h3V6h2v3z" fill="#F4F6F8" />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M10 1a9 9 0 100 18 9 9 0 000-18zm-7 9a7 7 0 1114 0 7 7 0 01-14 0z"
      fill="#F4F6F8"
    />
    <path d="M22.707 21.293l-4-4-1.414 1.414 4 4 1.414-1.414z" fill="#F4F6F8" />
  </svg>
))
SvgControlsZoomIn.displayName = 'SvgControlsZoomIn'
