// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgControlsPrevious = React.memo((props: React.SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path fillRule="evenodd" clipRule="evenodd" d="M9 12l11 7V5L9 12zm-5 7h2V5H4v14z" fill="#F4F6F8" />
  </svg>
))
SvgControlsPrevious.displayName = 'SvgControlsPrevious'
