// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgControlsSubtitlesOutline = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M3 3a2 2 0 00-2 2v12a2 2 0 002 2h2v.234c0 1.554 1.696 2.515 3.029 1.715L11.277 19H21a2 2 0 002-2V5a2 2 0 00-2-2H3zm0 2h18v12H10.723l-.238.142L7 19.234V17H3V5zm10 8H9v2h4v-2zm-8 0h2v2H5v-2zm14 0h-4v2h4v-2z"
      fill="#F4F6F8"
    />
  </svg>
)
