// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgControlsSoundOn = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M6 9l4-5h2v16h-2l-4-5H3a1 1 0 01-1-1v-4a1 1 0 011-1h3z" fill="#F4F6F8" />
    <path fillRule="evenodd" clipRule="evenodd" d="M20 12a6 6 0 00-6-6V4a8 8 0 110 16v-2a6 6 0 006-6z" fill="#F4F6F8" />
    <path fillRule="evenodd" clipRule="evenodd" d="M16 12a2 2 0 00-2-2V8a4 4 0 010 8v-2a2 2 0 002-2z" fill="#F4F6F8" />
  </svg>
)
