// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgGlyphPlay = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M8 14A6 6 0 108 2a6 6 0 000 12zm.5-7.5L6 5v6l2.5-1.5L11 8 8.5 6.5z"
      fill="#F4F6F8"
    />
  </svg>
)
