// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgGlyphResize = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path fill="#F4F6F8" d="M12.415 15.243L11 13.828 13.829 11l1.414 1.414zM6.414 14.9L5 13.486 13.485 5 14.9 6.415z" />
  </svg>
)
