// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgGlyphCopy = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <rect x={2} y={6} width={8} height={8} rx={1} fill="#F4F6F8" />
    <path fill="#F4F6F8" d="M6 2h8v2H6z" />
    <path fill="#F4F6F8" d="M12 10V2h2v8z" />
  </svg>
)
