// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgGlyphNewTab = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M5 11l3-3 3 3M8 8v7" stroke="#F4F6F8" strokeWidth={2} />
    <path d="M2 13V3a1 1 0 011-1h10a1 1 0 011 1v10" stroke="#F4F6F8" strokeWidth={2} />
    <path d="M14 10v3a1 1 0 01-1 1h-2m-9-4v3a1 1 0 001 1h2M3 4h10" stroke="#F4F6F8" strokeWidth={2} />
  </svg>
)
