// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgGlyphZoomIn = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M11 11l3 3" stroke="#F4F6F8" strokeWidth={2} />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M14 8A6 6 0 112 8a6 6 0 0112 0zM7 9H4V7h3V4h2v3h3v2H9v3H7V9z"
      fill="#F4F6F8"
    />
  </svg>
)
