// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgIllustrativePlay = React.memo((props: React.SVGProps<SVGSVGElement>) => (
  <svg width={48} height={48} viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M30 24l-9-6v12l9-6z" fill="#F4F6F8" />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M24 7C14.611 7 7 14.611 7 24s7.611 17 17 17 17-7.611 17-17S33.389 7 24 7zM9 24c0-8.284 6.716-15 15-15 8.284 0 15 6.716 15 15 0 8.284-6.716 15-15 15-8.284 0-15-6.716-15-15z"
      fill="#F4F6F8"
    />
  </svg>
))
SvgIllustrativePlay.displayName = 'SvgIllustrativePlay'
