// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgIllustrativeImage = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={48} height={48} viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M5 5a2 2 0 00-2 2v26a2 2 0 002 2h20v-2H5V7h30v16h2V7a2 2 0 00-2-2H5z" fill="#F4F6F8" />
    <path d="M25 17.5L7 27v4h18v-4a4 4 0 014-4l-4-5.5z" fill="#F4F6F8" />
    <path
      d="M45 27a2 2 0 00-2-2H29a2 2 0 00-2 2v14a2 2 0 002 2h8v-8.586l2 2L40.414 35 36 30.586 31.586 35 33 36.414l2-2V41h-6V27h14v14h-4v2h4a2 2 0 002-2V27zM12 17a3 3 0 100-6 3 3 0 000 6z"
      fill="#F4F6F8"
    />
  </svg>
)
