// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgIllustrativeEdit = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={48} height={48} viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      d="M32.293 7.679a1 1 0 011.4.014l4.585 4.585a1 1 0 01-.014 1.429l-2.114 2.029-6-6 2.143-2.057zM28.707 11.121l6 6L14 37H8v-6l20.707-19.879zM8 41h32v-2H8v2z"
      fill="#F4F6F8"
    />
  </svg>
)
