// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgIllustrativeFileSelected = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={48} height={48} viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M9 43h30V15L28 5H9v38z" stroke="#F4F6F8" strokeWidth={2} strokeLinejoin="round" strokeDasharray="8 2" />
    <path d="M28 15V5l11 10H28z" fill="#F4F6F8" stroke="#F4F6F8" strokeWidth={2} strokeLinejoin="round" />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M21.951 30.537l6.296-7.195 1.506 1.317-7.704 8.804-3.756-3.756 1.414-1.414 2.244 2.244z"
      fill="#F4F6F8"
    />
  </svg>
)
