// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgMember = React.memo((props: React.SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M8 15A7 7 0 108 1a7 7 0 000 14zm0-8a2 2 0 100-4 2 2 0 000 4zm0 6a5 5 0 004.546-2.916A5.986 5.986 0 008 8a5.986 5.986 0 00-4.546 2.084A5 5 0 008 13z"
      fill="#F4F6F8"
    />
  </svg>
))
SvgMember.displayName = 'SvgMember'
