// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgNavChannel = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <circle cx={12} cy={9} r={3} stroke="#F4F6F8" strokeWidth={2} />
    <path
      d="M10 22h7a1 1 0 001-1v-1a4 4 0 00-4-4h-4a4 4 0 00-4 4v2"
      stroke="#F4F6F8"
      strokeWidth={2}
      strokeMiterlimit={10}
      strokeLinecap="square"
    />
    <path
      d="M12 22h9a1 1 0 001-1V3a1 1 0 00-1-1H3a1 1 0 00-1 1v18a1 1 0 001 1h1.5"
      stroke="#F4F6F8"
      strokeWidth={2}
      strokeMiterlimit={10}
      strokeLinecap="square"
    />
  </svg>
)
