// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgOutlineZoomIn = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <circle cx={10} cy={10} r={8} stroke="#F4F6F8" strokeWidth={2} />
    <path d="M22 22l-4-4M14 10H6M10 6v8" stroke="#F4F6F8" strokeWidth={2} strokeMiterlimit={10} />
  </svg>
)
