// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgOutlineFileImage = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <rect x={3} y={5} width={18} height={14} rx={1} stroke="#F4F6F8" strokeWidth={2} />
    <path d="M18 14l-4-4-8 4v2h12v-2z" fill="#F4F6F8" />
    <circle cx={7} cy={9} r={1} fill="#F4F6F8" />
  </svg>
)
