// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgPlayerCancel = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M2 12C2 6.477 6.477 2 12 2s10 4.477 10 10-4.477 10-10 10S2 17.523 2 12zm10 8A8 8 0 015.68 7.094L16.906 18.32A7.966 7.966 0 0112 20zm6.32-3.094A8 8 0 007.094 5.68L18.32 16.906z"
      fill="#F4F6F8"
    />
  </svg>
)
