// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgSidebarChannels = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M16 3a4 4 0 100 8 4 4 0 000-8zm-2 4a2 2 0 114 0 2 2 0 01-4 0z"
      fill="#F4F6F8"
    />
    <path
      d="M6 5a2 2 0 100 4 2 2 0 000-4zM12.5 19H21v-1a3 3 0 00-3-3h-4a3 3 0 00-3 3v1.5H9V18c0-.343.034-.677.1-1H5v-2h3.991A2.2 2.2 0 006.8 13H5a2 2 0 00-2 2v2H1v-2a4 4 0 014-4h1.8a4.202 4.202 0 014.057 3.11A4.98 4.98 0 0114 13h4a5 5 0 015 5v1a2 2 0 01-2 2h-8.5v-2z"
      fill="#F4F6F8"
    />
  </svg>
)
