// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgSidebarFollowingAlt = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M1 3a2 2 0 012-2h18a2 2 0 012 2v10h-2V3H3v18h7.5v2H3a2 2 0 01-2-2V3z" fill="#F4F6F8" />
    <path d="M7 13h10v2H7v-2zM17 9H7v2h10V9z" fill="#F4F6F8" />
  </svg>
)
