// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgSidebarHome = React.memo((props: React.SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M10 21.002A1.999 1.999 0 018 23H3a2 2 0 01-2-2v-9.555a2 2 0 01.662-1.486L12 .655l10.338 9.304A2 2 0 0123 11.445V21a2 2 0 01-2 2h-5a2 2 0 01-2-2v-2h2v2h5v-9.555l-9-8.1-9 8.1V21h5v-4a2 2 0 012-2h6v2h-6v4.002z"
      fill="#F4F6F8"
    />
  </svg>
))
SvgSidebarHome.displayName = 'SvgSidebarHome'
