// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgSocialMediaTelegramMonochrome = React.memo((props: React.SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      d="M3.375 11.14c5.369-2.34 8.949-3.882 10.74-4.627 5.114-2.127 6.177-2.497 6.87-2.509.152-.003.493.035.713.214.186.151.238.356.262.499.025.143.055.47.031.725-.277 2.912-1.476 9.979-2.086 13.24-.259 1.38-.767 1.843-1.259 1.888-1.07.099-1.881-.706-2.917-1.385-1.621-1.063-2.537-1.724-4.11-2.761-1.818-1.198-.64-1.857.396-2.933.272-.282 4.984-4.568 5.075-4.957.011-.048.022-.23-.086-.325-.108-.096-.266-.063-.381-.037-.163.037-2.752 1.748-7.768 5.134-.735.505-1.4.75-1.997.738-.658-.014-1.923-.372-2.863-.678-1.153-.374-2.07-.573-1.99-1.21.041-.33.498-.67 1.37-1.017z"
      fill="#fff"
    />
  </svg>
))
SvgSocialMediaTelegramMonochrome.displayName = 'SvgSocialMediaTelegramMonochrome'
