// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgSocialMediaMessengerOnLight = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M12 2.86c-5.281 0-9.375 3.868-9.375 9.093 0 2.733 1.12 5.095 2.944 6.726.153.137.246.33.252.535l.051 1.668a.75.75 0 001.053.663l1.86-.822a.748.748 0 01.501-.037c.855.236 1.765.36 2.714.36 5.281 0 9.375-3.868 9.375-9.093S17.281 2.86 12 2.86z"
      fill="url(#social-media-messenger-on-light_svg__paint0_radial_603_409)"
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M6.37 14.615l2.754-4.37a1.406 1.406 0 012.034-.374l2.19 1.642c.2.151.477.15.678-.002l2.958-2.245c.394-.3.91.173.646.592l-2.754 4.37a1.406 1.406 0 01-2.034.375l-2.19-1.643a.562.562 0 00-.678.002l-2.958 2.245c-.395.3-.91-.173-.646-.592z"
      fill="#fff"
    />
    <defs>
      <radialGradient
        id="social-media-messenger-on-light_svg__paint0_radial_603_409"
        cx={0}
        cy={0}
        r={1}
        gradientUnits="userSpaceOnUse"
        gradientTransform="translate(6.234 21.51) scale(20.4299)"
      >
        <stop stopColor="#09F" />
        <stop offset={0.61} stopColor="#A033FF" />
        <stop offset={0.935} stopColor="#FF5280" />
        <stop offset={1} stopColor="#FF7061" />
      </radialGradient>
    </defs>
  </svg>
)
