// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgSocialMediaTwitterOnDark = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      d="M22 5.925a8.217 8.217 0 01-2.356.645 4.114 4.114 0 001.804-2.27c-.793.47-1.671.812-2.606.995a4.104 4.104 0 00-6.992 3.744A11.652 11.652 0 013.393 4.75a4.104 4.104 0 001.27 5.479 4.093 4.093 0 01-1.859-.513v.053a4.105 4.105 0 003.292 4.023 4.132 4.132 0 01-1.853.07 4.106 4.106 0 003.833 2.85 8.234 8.234 0 01-5.097 1.756c-.33 0-.658-.019-.979-.057a11.605 11.605 0 006.29 1.844c7.548 0 11.674-6.252 11.674-11.675 0-.176-.004-.354-.012-.53a8.342 8.342 0 002.046-2.123L22 5.925z"
      fill="#1DA1F2"
    />
  </svg>
)
