// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgSocialMediaFacebookMonochrome = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M12.155 21.998zm1.407-.12v-6.987h2.33L16.337 12h-2.774v-1.876c0-.79.387-1.562 1.63-1.562h1.262V6.1s-1.145-.196-2.24-.196c-2.283 0-3.776 1.384-3.776 3.891V12h-2.54v2.891h2.54v6.987C5.657 21.128 2 16.991 2 12 2 6.477 6.477 2 12 2s10 4.477 10 10c0 4.991-3.657 9.128-8.438 9.878z"
      fill="#fff"
    />
  </svg>
)
