name = "atlas-proxy-worker"
type = "javascript"
account_id = ""
route = ""
compatibility_date = "2022-06-15"
workers_dev = true

[vars]
ATLAS_URL = "https://atlas-js.vercel.app"
META_SERVER_URL = "https://atlas-services.joystream.org/social-previews"

[build]
command = "yarn install --immutable && yarn build"
[build.upload]
format = "service-worker"

[env.production]
zone_id = "9b5baa89abf2e9aecd90951a5d561f04"
routes = ["play.joystream.org/channel/*", "play.joystream.org/video/*"]

[env.production.vars]
ATLAS_URL = "https://atlas-js.vercel.app"
META_SERVER_URL = "https://atlas-services.joystream.org/social-previews"
