// eslint-disable-next-line @typescript-eslint/no-var-requires
const path = require('path')

module.exports = {
  template: componentTemplate,
  indexTemplate: indexTemplate,
  typescript: true,
  memo: true,
  prettier: true,
  svgoConfig: {
    plugins: [
      {
        name: 'preset-default',
        params: {
          overrides: {
            removeViewBox: false,
          },
        },
      },
    ],
  },
}

const comment = '// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY'

function componentTemplate(variables, { tpl }) {
  return tpl`
${comment}

${variables.imports}

${variables.interfaces}

const ${variables.componentName} = (${variables.props}) => (
  ${variables.jsx}
)

const Memo = memo(${variables.componentName})
export { Memo as ${variables.componentName} }
`
}

function indexTemplate(filePaths) {
  const exportEntries = filePaths.map((filePath) => {
    const basename = path.basename(filePath, path.extname(filePath))
    return `export * from './${basename}'`
  })
  return comment + '\n' + exportEntries.join('\n') + '\n'
}
