// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { SVGProps, memo } from 'react'

const SvgAvatarSilhouette = (props: SVGProps<SVGSVGElement>) => (
  <svg width={136} height={136} viewBox="0 0 136 136" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M68 136c37.555 0 68-30.445 68-68S105.555 0 68 0 0 30.445 0 68s30.445 68 68 68Z" fill="#181C20" />
    <mask
      id="mask0_1008_6546"
      style={{
        maskType: 'alpha',
      }}
      maskUnits="userSpaceOnUse"
      x={0}
      y={0}
      width={136}
      height={136}
    >
      <path d="M68 136c37.555 0 68-30.445 68-68S105.555 0 68 0 0 30.445 0 68s30.445 68 68 68Z" fill="#181C20" />
    </mask>
    <g mask="url(#mask0_1008_6546)">
      <path
        d="M68 78.578c13.353 0 24.178-10.825 24.178-24.178 0-13.353-10.825-24.178-24.178-24.178-13.353 0-24.178 10.825-24.178 24.178 0 13.353 10.825 24.178 24.178 24.178ZM25.689 120.889c0-16.691 13.53-30.222 30.222-30.222h24.178c16.691 0 30.222 13.531 30.222 30.222v58.933c0 16.692-13.53 30.222-30.222 30.222H55.91c-16.691 0-30.222-13.53-30.222-30.222v-58.933Z"
        fill="#424E57"
      />
      <path
        d="M68 135c37.003 0 67-29.997 67-67S105.003 1 68 1 1 30.997 1 68s29.997 67 67 67Z"
        stroke="#181C20"
        strokeWidth={2}
      />
    </g>
  </svg>
)

const Memo = memo(SvgAvatarSilhouette)
export { Memo as SvgAvatarSilhouette }
