// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'
import { SVGProps, memo } from 'react'

const SvgAvatarSilhouette = (props: SVGProps<SVGSVGElement>) => (
  <svg width={136} height={136} viewBox="0 0 136 136" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <circle cx={68} cy={68} r={68} fill="#181C20" />
    <mask id="avatar-silhouette" mask-type="alpha" maskUnits="userSpaceOnUse" x={0} y={0} width={136} height={136}>
      <circle cx={68} cy={68} r={68} fill="#181C20" />
    </mask>
    <g mask="url(#avatar-silhouette)" fill="#424E57">
      <circle cx={68} cy={54.4} r={24.178} />
      <path d="M25.689 120.889c0-16.691 13.53-30.222 30.222-30.222H80.09c16.691 0 30.222 13.531 30.222 30.222v58.933c0 16.692-13.53 30.222-30.222 30.222H55.91c-16.691 0-30.222-13.53-30.222-30.222v-58.933Z" />
    </g>
    <circle cx={68} cy={68} r={67} stroke="#181C20" strokeWidth={2} />
  </svg>
)

const Memo = memo(SvgAvatarSilhouette)
export { Memo as SvgAvatarSilhouette }
