// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgJoystreamLogoShort = React.memo((props: React.SVGProps<SVGSVGElement>) => (
  <svg width={26} height={32} fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <g clipPath="url(#joystream-logo-short_svg__a)" fill="#4038FF">
      <path d="M16.96.016l2.922.007-.036 13.676a13.065 13.065 0 01-3.321 8.677c.26-1.127.394-2.28.396-3.438l.04-18.922zm-9.397 23.85a7.823 7.823 0 01-5.982 2.892l.88-2.906 5.102.014zm1.788-5.235v.291a7.793 7.793 0 01-.458 2.618l-5.73-.016.875-2.909 5.313.016zM22.211.03h2.91L25.1 8.48a13.064 13.064 0 01-3.326 8.677c.261-1.127.394-2.28.397-3.438L22.21.03z" />
      <path d="M14.64 0l-.05 18.93A13.112 13.112 0 011.456 31.992H0l.878-2.908h.584A10.202 10.202 0 0011.69 18.927L11.728 0h2.913z" />
    </g>
    <defs>
      <clipPath id="joystream-logo-short_svg__a">
        <path fill="#fff" d="M0 0h25.122v32H0z" />
      </clipPath>
    </defs>
  </svg>
))
SvgJoystreamLogoShort.displayName = 'SvgJoystreamLogoShort'
