// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { SVGProps, memo } from 'react'

const SvgJoystreamLogoIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg width={40} height={40} viewBox="0 0 40 40" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M40 20C40 8.954 31.046 0 20 0S0 8.954 0 20s8.954 20 20 20 20-8.954 20-20Z" fill="#4038FF" />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M22.5 9h1.96v9.25c0 2.25-.84 4.3-2.23 5.87.17-.75.27-1.53.27-2.33V9Zm-6.41 16.12a5.301 5.301 0 0 1-4.05 1.97l.59-1.97h3.46Zm1.17-3.34v-.2h-3.6l-.58 1.97h3.88c.2-.55.3-1.15.3-1.77ZM26.03 9H28v5.71c0 2.25-.84 4.3-2.23 5.87.17-.75.26-1.53.26-2.33V9Zm-5.19 12.8V9h-1.97v12.8a6.9 6.9 0 0 1-6.89 6.9h-.4L11 30.65h.98a8.87 8.87 0 0 0 8.86-8.86v.01Z"
      fill="#fff"
    />
  </svg>
)

const Memo = memo(SvgJoystreamLogoIcon)
export { Memo as SvgJoystreamLogoIcon }
