// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'
import { SVGProps, memo } from 'react'

const SvgPolkadotLogoIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="15 15 140 140"
    style={{
      zoom: 1,
    }}
    {...props}
  >
    <circle cx={85} cy={85} r={70} fill="#ff8c00" />
    <path
      fill="#fff"
      d="M85 34.7c-20.8 0-37.8 16.9-37.8 37.8 0 4.2.7 8.3 2 12.3.9 2.7 3.9 4.2 6.7 3.3 2.7-.9 4.2-3.9 3.3-6.7-1.1-3.1-1.6-6.4-1.5-9.7.4-14.1 11.8-25.7 25.9-26.4 15.7-.8 28.7 11.7 28.7 27.2 0 14.5-11.4 26.4-25.7 27.2 0 0-5.3.3-7.9.7-1.3.2-2.3.4-3 .5-.3.1-.6-.2-.5-.5l.9-4.4L81 73.4c.6-2.8-1.2-5.6-4-6.2-2.8-.6-5.6 1.2-6.2 4 0 0-11.8 55-11.9 55.6-.6 2.8 1.2 5.6 4 6.2 2.8.6 5.6-1.2 6.2-4 .1-.6 1.7-7.9 1.7-7.9 1.2-5.6 5.8-9.7 11.2-10.4 1.2-.2 5.9-.5 5.9-.5a37.84 37.84 0 0 0 34.9-37.7c0-20.9-17-37.8-37.8-37.8zm2.7 87a6.3 6.3 0 0 0-7.5 4.9 6.3 6.3 0 0 0 4.9 7.5c3.4.7 6.8-1.4 7.5-4.9.7-3.5-1.4-6.8-4.9-7.5z"
    />
  </svg>
)

const Memo = memo(SvgPolkadotLogoIcon)
export { Memo as SvgPolkadotLogoIcon }
