version: '3.7'
services:
  node:
    build:
      context: ../
      dockerfile: ./packages/atlas-meta-server/Dockerfile
    environment:
      - PORT=${DOCKER_NODE_PORT}
      - GRAPHQL_URL=https://hydra.joystream.org/graphql
    ports:
      - '${DOCKER_NODE_PORT}:${DOCKER_NODE_PORT}'
  atlas:
    depends_on:
      - node
    volumes:
      - ../packages/atlas/nginx:/etc/nginx/templates
    build:
      context: ../
      target: nginx
      dockerfile: ./packages/atlas/Dockerfile
    environment:
      - NODE_PORT=${DOCKER_NODE_PORT}
    ports:
      - '80:80'
    restart: always
