// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgBenefitCardPatternXxs1 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    width={144}
    height={144}
    viewBox="0 0 144 144"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    ref={ref}
    {...props}
  >
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M107.923 110.82V108h2.82l33.18 33.18V144h-2.819l-33.181-33.18Zm36 24.54v-5.627L122.19 108h-5.627l27.36 27.36Zm0-16.82v5.66l-16.2-16.2h5.66l10.54 10.54Zm0-10.54h-5.04l5.04 5.04V108Zm-8.64 36h-5.627l-21.733-21.733v-5.627l27.36 27.36Zm-16.82 0h5.66l-16.2-16.2v5.66l10.54 10.54Zm-10.54-5.04 5.04 5.04h-5.04v-5.04Z"
      fill="#C2E0FF"
      fillOpacity={0.2}
    />
    <g clipPath="url(#clip0_1505_4256)" fill="#BCD5FA" fillOpacity={0.08}>
      <path d="M36 143.987v-4.002c17.43-.519 31.466-14.554 31.985-31.985h4.002C71.466 127.64 55.64 143.466 36 143.987Z" />
      <path d="M63.983 108c-.516 15.221-12.762 27.467-27.983 27.983v-4.003c13.012-.511 23.468-10.968 23.98-23.98h4.003Z" />
      <path d="M56 108c0 11.046-8.954 20-20 20v-4c8.837 0 16-7.163 16-16h4Z" />
      <path d="M48 108c0 6.627-5.373 12-12 12v-4a8 8 0 0 0 8-8h4ZM40 108a4 4 0 0 1-4 4v-4h4Z" />
    </g>
    <g clipPath="url(#clip1_1505_4256)">
      <path d="M108 107.987C88.36 107.466 72.534 91.64 72.013 72H108v35.987Z" fill="#BCD5FA" fillOpacity={0.08} />
    </g>
    <path
      d="M144 72h-4v-4h4v4ZM132 52h4v4h-4v-4ZM128 52v4h-4v-4h4ZM128 48v4h4v-4h4v-4h-4v4h-4ZM124 48v-4h4v4h-4ZM120 48h4v4h-4v-4ZM120 56h-4v-4h4v4ZM120 60h-4v4h4v-4ZM120 60v-4h4v4h-4ZM120 48v-4h-4v4h4Z"
      fill="#C2E0FF"
      fillOpacity={0.2}
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M136 68h4v-4h4v-4h-4v-4h4v-4h-4v-4h4v-4h-4v-4h4v-4h-4v4h-4v-4h-4v4h-4v-4h-4v4h-4v-4h-4v4h-4v-4h-4v4h4v4h-4v4h4v4h-4v4h4v4h-4v4h4v4h-4v4h4v-4h4v4h4v-4h4v4h4v-4h4v4h4v-4Zm0-4v4h-4v-4h4Zm0-4v4h4v-4h-4Zm-4 0v4h-4v-4h4Zm0-4v4h4v-4h4v-4h-4v-4h4v-4h-4v-4h-4v4h-4v-4h-4v4h-4v-4h-4v4h-4v4h4v4h-4v4h4v4h-4v4h4v4h4v-4h4v4h4v-4h-4v-4h4v-4h4Z"
      fill="#C2E0FF"
      fillOpacity={0.2}
    />
    <path
      d="M0 72h4v4H0v-4ZM12 92H8v-4h4v4ZM16 92v-4h4v4h-4ZM16 96v-4h-4v4H8v4h4v-4h4ZM20 96v4h-4v-4h4ZM24 96h-4v-4h4v4ZM24 88h4v4h-4v-4ZM24 84h4v-4h-4v4ZM24 84v4h-4v-4h4ZM24 96v4h4v-4h-4Z"
      fill="#C2E0FF"
      fillOpacity={0.2}
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M8 76H4v4H0v4h4v4H0v4h4v4H0v4h4v4H0v4h4v-4h4v4h4v-4h4v4h4v-4h4v4h4v-4h4v4h4v-4h-4v-4h4v-4h-4v-4h4v-4h-4v-4h4v-4h-4v-4h4v-4h-4v4h-4v-4h-4v4h-4v-4h-4v4h-4v-4H8v4Zm0 4v-4h4v4H8Zm0 4v-4H4v4h4Zm4 0v-4h4v4h-4Zm0 4v-4H8v4H4v4h4v4H4v4h4v4h4v-4h4v4h4v-4h4v4h4v-4h4v-4h-4v-4h4v-4h-4v-4h4v-4h-4v-4h-4v4h-4v-4h-4v4h4v4h-4v4h-4Z"
      fill="#C2E0FF"
      fillOpacity={0.2}
    />
    <g clipPath="url(#clip2_1505_4256)">
      <path d="M36 36.013C55.64 36.534 71.466 52.36 71.987 72H36V36.013Z" fill="#BCD5FA" fillOpacity={0.08} />
    </g>
    <g clipPath="url(#clip3_1505_4256)" fill="#BCD5FA" fillOpacity={0.08}>
      <path d="M108 .013v4.002C90.57 4.534 76.534 18.569 76.015 36h-4.002C72.534 16.36 88.36.534 108 .013Z" />
      <path d="M80.017 36C80.533 20.779 92.779 8.533 108 8.017v4.003C94.988 12.53 84.531 22.988 84.02 36h-4.003Z" />
      <path d="M88 36c0-11.046 8.954-20 20-20v4c-8.837 0-16 7.163-16 16h-4Z" />
      <path d="M96 36c0-6.627 5.373-12 12-12v4a8 8 0 0 0-8 8h-4ZM104 36a4 4 0 0 1 4-4v4h-4Z" />
    </g>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M36.077 33.18V36h-2.82L.077 2.82V0h2.82l33.18 33.18Zm-36-24.54v5.627L21.81 36h5.627L.077 8.64Zm0 16.82V19.8l16.2 16.2h-5.66L.077 25.46Zm0 10.54h5.04l-5.04-5.04V36Zm8.64-36h5.627l21.733 21.733v5.627L8.717 0Zm16.82 0h-5.66l16.2 16.2v-5.66L25.537 0Zm10.54 5.04L31.037 0h5.04v5.04Z"
      fill="#C2E0FF"
      fillOpacity={0.2}
    />
    <defs>
      <clipPath id="clip0_1505_4256">
        <path fill="#fff" transform="matrix(1 0 0 -1 36 144)" d="M0 0h36v36H0z" />
      </clipPath>
      <clipPath id="clip1_1505_4256">
        <path fill="#fff" transform="rotate(-180 54 54)" d="M0 0h36v36H0z" />
      </clipPath>
      <clipPath id="clip2_1505_4256">
        <path fill="#fff" transform="translate(36 36)" d="M0 0h36v36H0z" />
      </clipPath>
      <clipPath id="clip3_1505_4256">
        <path fill="#fff" transform="matrix(-1 0 0 1 108 0)" d="M0 0h36v36H0z" />
      </clipPath>
    </defs>
  </svg>
))
SvgBenefitCardPatternXxs1.displayName = 'SvgBenefitCardPatternXxs1'
const Memo = memo(SvgBenefitCardPatternXxs1)
export { Memo as SvgBenefitCardPatternXxs1 }
