// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgBenefitCardPatternSm3 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    width={216}
    height={216}
    viewBox="0 0 216 216"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    ref={ref}
    {...props}
  >
    <g clipPath="url(#clip0_1505_4346)" fill="#C2E0FF" fillOpacity={0.2}>
      <path d="M216 215.98v-6.002c-26.146-.779-47.2-21.832-47.978-47.978h-6.002c.782 29.46 24.52 53.198 53.98 53.98Z" />
      <path d="M174.025 162c.774 22.832 19.143 41.201 41.975 41.974v-6.004c-19.518-.767-35.203-16.452-35.971-35.97h-6.004Z" />
      <path d="M186 162c0 16.568 13.431 30 30 30v-6c-13.255 0-24-10.745-24-24h-6Z" />
      <path d="M198 162c0 9.941 8.059 18 18 18v-6c-6.627 0-12-5.373-12-12h-6ZM210 162a6 6 0 0 0 6 6v-6h-6Z" />
    </g>
    <g clipPath="url(#clip1_1505_4346)" fill="#BCD5FA" fillOpacity={0.08}>
      <path d="M108 210H54v6h54v-6ZM108 162H54v6h54v-6ZM54 174h54v6H54v-6ZM108 198H54v6h54v-6ZM54 186h54v6H54v-6Z" />
    </g>
    <path
      d="M162 162h-6v-6h6v6ZM144 132h6v6h-6v-6ZM138 132v6h-6v-6h6ZM138 126v6h6v-6h6v-6h-6v6h-6ZM132 126v-6h6v6h-6ZM126 126h6v6h-6v-6ZM126 138h-6v-6h6v6ZM126 144h-6v6h6v-6ZM126 144v-6h6v6h-6ZM126 126v-6h-6v6h6Z"
      fill="#BCD5FA"
      fillOpacity={0.08}
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M150 156h6v-6h6v-6h-6v-6h6v-6h-6v-6h6v-6h-6v-6h6v-6h-6v6h-6v-6h-6v6h-6v-6h-6v6h-6v-6h-6v6h-6v-6h-6v6h6v6h-6v6h6v6h-6v6h6v6h-6v6h6v6h-6v6h6v-6h6v6h6v-6h6v6h6v-6h6v6h6v-6Zm0-6v6h-6v-6h6Zm0-6v6h6v-6h-6Zm-6 0v6h-6v-6h6Zm0-6v6h6v-6h6v-6h-6v-6h6v-6h-6v-6h-6v6h-6v-6h-6v6h-6v-6h-6v6h-6v6h6v6h-6v6h6v6h-6v6h6v6h6v-6h6v6h6v-6h-6v-6h6v-6h6Z"
      fill="#BCD5FA"
      fillOpacity={0.08}
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M54.115 112.23V108h-4.23L.115 157.77V162h4.23l49.77-49.77Zm-54 36.81v-8.441L32.715 108h8.44L.115 149.04Zm0-25.23v8.49l24.3-24.3h-8.49L.115 123.81Zm0-15.81h7.56l-7.56 7.56V108Zm12.96 54h8.44l32.6-32.599v-8.441L13.075 162Zm25.23 0h-8.49l24.3-24.3v8.49L38.305 162Zm15.81-7.56-7.56 7.56h7.56v-7.56ZM161.885 103.77V108h4.23l49.77-49.77V54h-4.23l-49.77 49.77Zm54-36.81v8.44l-32.6 32.6h-8.44l41.04-41.04Zm0 25.23V83.7l-24.3 24.3h8.49l15.81-15.81Zm0 15.81h-7.56l7.56-7.56V108Zm-12.96-54h-8.441l-32.599 32.6v8.44L202.925 54Zm-25.23 0h8.49l-24.3 24.3v-8.49L177.695 54Zm-15.81 7.56 7.56-7.56h-7.56v7.56Z"
      fill="#C2E0FF"
      fillOpacity={0.2}
    />
    <path
      d="M54 54h6v6h-6v-6ZM72 84h-6v-6h6v6ZM78 84v-6h6v6h-6ZM78 90v-6h-6v6h-6v6h6v-6h6ZM84 90v6h-6v-6h6ZM90 90h-6v-6h6v6ZM90 78h6v6h-6v-6ZM90 72h6v-6h-6v6ZM90 72v6h-6v-6h6ZM90 90v6h6v-6h-6Z"
      fill="#BCD5FA"
      fillOpacity={0.08}
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M66 60h-6v6h-6v6h6v6h-6v6h6v6h-6v6h6v6h-6v6h6v-6h6v6h6v-6h6v6h6v-6h6v6h6v-6h6v6h6v-6h-6v-6h6v-6h-6v-6h6v-6h-6v-6h6v-6h-6v-6h6v-6h-6v6h-6v-6h-6v6h-6v-6h-6v6h-6v-6h-6v6Zm0 6v-6h6v6h-6Zm0 6v-6h-6v6h6Zm6 0v-6h6v6h-6Zm0 6v-6h-6v6h-6v6h6v6h-6v6h6v6h6v-6h6v6h6v-6h6v6h6v-6h6v-6h-6v-6h6v-6h-6v-6h6v-6h-6v-6h-6v6h-6v-6h-6v6h6v6h-6v6h-6Z"
      fill="#BCD5FA"
      fillOpacity={0.08}
    />
    <g clipPath="url(#clip2_1505_4346)" fill="#BCD5FA" fillOpacity={0.08}>
      <path d="M108 6h54V0h-54v6ZM108 54h54v-6h-54v6ZM162 42h-54v-6h54v6ZM108 18h54v-6h-54v6ZM162 30h-54v-6h54v6Z" />
    </g>
    <g clipPath="url(#clip3_1505_4346)" fill="#C2E0FF" fillOpacity={0.2}>
      <path d="M0 .02v6.002C26.146 6.801 47.2 27.854 47.978 54h6.002C53.198 24.54 29.46.802 0 .02Z" />
      <path d="M41.975 54C41.2 31.168 22.832 12.8 0 12.026v6.004c19.518.767 35.203 16.452 35.97 35.97h6.005Z" />
      <path d="M30 54c0-16.568-13.431-30-30-30v6c13.255 0 24 10.745 24 24h6Z" />
      <path d="M18 54c0-9.941-8.059-18-18-18v6c6.627 0 12 5.373 12 12h6ZM6 54a6 6 0 0 0-6-6v6h6Z" />
    </g>
    <defs>
      <clipPath id="clip0_1505_4346">
        <path fill="#fff" transform="rotate(-180 108 108)" d="M0 0h54v54H0z" />
      </clipPath>
      <clipPath id="clip1_1505_4346">
        <path fill="#fff" transform="matrix(1 0 0 -1 54 216)" d="M0 0h54v54H0z" />
      </clipPath>
      <clipPath id="clip2_1505_4346">
        <path fill="#fff" transform="matrix(-1 0 0 1 162 0)" d="M0 0h54v54H0z" />
      </clipPath>
      <clipPath id="clip3_1505_4346">
        <path fill="#fff" d="M0 0h54v54H0z" />
      </clipPath>
    </defs>
  </svg>
))
SvgBenefitCardPatternSm3.displayName = 'SvgBenefitCardPatternSm3'
const Memo = memo(SvgBenefitCardPatternSm3)
export { Memo as SvgBenefitCardPatternSm3 }
