// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgHoldersPlaceholder = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    width={259}
    height={128}
    viewBox="0 0 259 128"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    ref={ref}
    {...props}
  >
    <path fill="#343D44" d="M8 8h24v24H8z" />
    <g clipPath="url(#clip0_2780_776)">
      <rect x={42} y={8} width={24} height={24} rx={12} fill="#343D44" />
    </g>
    <rect x={42.5} y={8.5} width={23} height={23} rx={11.5} stroke="#BCD5FA" strokeOpacity={0.08} />
    <path fill="#343D44" d="M76 12h82v16H76zM219 12h32v16h-32z" />
    <path fill="#272D33" d="M8 52h24v24H8z" />
    <g clipPath="url(#clip1_2780_776)">
      <rect x={42} y={52} width={24} height={24} rx={12} fill="#272D33" />
    </g>
    <rect x={42.5} y={52.5} width={23} height={23} rx={11.5} stroke="#BCD5FA" strokeOpacity={0.08} />
    <path fill="#272D33" d="M76 56h82v16H76zM219 56h32v16h-32z" />
    <path fill="#181C20" d="M8 96h24v24H8z" />
    <g clipPath="url(#clip2_2780_776)">
      <rect x={42} y={96} width={24} height={24} rx={12} fill="#181C20" />
    </g>
    <rect x={42.5} y={96.5} width={23} height={23} rx={11.5} stroke="#BCD5FA" strokeOpacity={0.08} />
    <path fill="#181C20" d="M76 100h82v16H76zM219 100h32v16h-32z" />
    <defs>
      <clipPath id="clip0_2780_776">
        <rect x={42} y={8} width={24} height={24} rx={12} fill="#fff" />
      </clipPath>
      <clipPath id="clip1_2780_776">
        <rect x={42} y={52} width={24} height={24} rx={12} fill="#fff" />
      </clipPath>
      <clipPath id="clip2_2780_776">
        <rect x={42} y={96} width={24} height={24} rx={12} fill="#fff" />
      </clipPath>
    </defs>
  </svg>
))
SvgHoldersPlaceholder.displayName = 'SvgHoldersPlaceholder'
const Memo = memo(SvgHoldersPlaceholder)
export { Memo as SvgHoldersPlaceholder }
