// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import { Ref, SVGProps, forwardRef, memo } from 'react'

const SvgPatternAngledLines = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg width={72} height={72} viewBox="0 0 72 72" fill="none" xmlns="http://www.w3.org/2000/svg" ref={ref} {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M72 66.36V72h-5.64L0 5.64V0h5.64L72 66.36ZM0 17.28v11.255L43.466 72H54.72L0 17.28Zm0 33.64V39.6L32.4 72H21.08L0 50.92ZM0 72h10.08L0 61.92V72ZM17.28 0h11.254L72 43.465V54.72L17.28 0Zm33.64 0H39.6L72 32.4V21.08L50.92 0ZM72 10.08 61.92 0H72v10.08Z"
      fill="#BBD9F6"
      fillOpacity={0.13}
    />
  </svg>
))
SvgPatternAngledLines.displayName = 'SvgPatternAngledLines'
const Memo = memo(SvgPatternAngledLines)
export { Memo as SvgPatternAngledLines }
