// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgControlsCaptionsOutline = React.memo((props: React.SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M1 5a2 2 0 012-2h18a2 2 0 012 2v14a2 2 0 01-2 2H3a2 2 0 01-2-2V5zm20 0H3v14h18V5zM5 9a2 2 0 012-2h2a2 2 0 012 2v2H9V9H7v6h2v-2h2v2a2 2 0 01-2 2H7a2 2 0 01-2-2V9zm10-2a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2v-2h-2v2h-2V9h2v2h2V9a2 2 0 00-2-2h-2z"
      fill="#F4F6F8"
    />
  </svg>
))
SvgControlsCaptionsOutline.displayName = 'SvgControlsCaptionsOutline'
