// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgControlsLink = React.memo((props: React.SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M1 9a2 2 0 012-2h7v2H3v6h7v2H3a2 2 0 01-2-2V9zm22 6a2 2 0 01-2 2h-7v-2h7V9h-7V7h7a2 2 0 012 2v6zM6 13h12v-2H6v2z"
      fill="#F4F6F8"
    />
  </svg>
))
SvgControlsLink.displayName = 'SvgControlsLink'
