// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgGlyphAddVideo = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M1 2a1 1 0 00-1 1v10a1 1 0 001 1h10a1 1 0 001-1V3a1 1 0 00-1-1H1zm4 2h2v3h3v2H7v3H5V9H2V7h3V4z"
      fill="#F4F6F8"
    />
    <path d="M12 7l3-3h1v8h-1l-3-3V7z" fill="#F4F6F8" />
  </svg>
)
