// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgGlyphLink = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      d="M7 7L3 3M8 13l-.293.293A2.414 2.414 0 016 14v0c-.64 0-1.254-.254-1.707-.707l-1.586-1.586A2.414 2.414 0 012 10v0c0-.64.254-1.254.707-1.707L3 8M8 3l.293-.293A2.414 2.414 0 0110 2v0c.64 0 1.254.254 1.707.707l1.586 1.586C13.746 4.746 14 5.36 14 6v0c0 .64-.254 1.254-.707 1.707L13 8M13 13L9 9"
      stroke="#F4F6F8"
      strokeWidth={2}
    />
  </svg>
)
