// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgIllustrativeImage = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={48} height={48} viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M7 27l18-9.5 4 5.5a4 4 0 00-4 4v4H7v-4z" fill="#F4F6F8" />
    <path d="M25 34H5a1 1 0 01-1-1V7a1 1 0 011-1h30a1 1 0 011 1v16" stroke="#F4F6F8" strokeWidth={2} />
    <path
      d="M36 42h-7a1 1 0 01-1-1V27a1 1 0 011-1h14a1 1 0 011 1v14a1 1 0 01-1 1h-3"
      stroke="#F4F6F8"
      strokeWidth={2}
      strokeMiterlimit={10}
      strokeLinecap="square"
    />
    <path d="M36 42V32" stroke="#F4F6F8" strokeWidth={2} strokeMiterlimit={10} />
    <path d="M33 35l3-3 3 3" stroke="#F4F6F8" strokeWidth={2} strokeMiterlimit={10} strokeLinecap="square" />
    <circle cx={12} cy={14} r={3} fill="#F4F6F8" />
  </svg>
)
