// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgOutlineSuccess = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={32} height={32} viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <circle cx={16} cy={16} r={15} stroke="#00DBB0" strokeWidth={2} />
    <path d="M11 17l3 3 7-8" stroke="#00DBB0" strokeWidth={2} />
  </svg>
)
