// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgOutlineExternal = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      d="M17 14v6a1 1 0 01-1 1H4a1 1 0 01-1-1V8a1 1 0 011-1h6"
      stroke="#F4F6F8"
      strokeWidth={2}
      strokeMiterlimit={10}
      strokeLinecap="square"
    />
    <path d="M21 3L11 13" stroke="#F4F6F8" strokeWidth={2} />
    <path d="M15 3h6v6" stroke="#F4F6F8" strokeWidth={2} strokeMiterlimit={10} strokeLinecap="square" />
  </svg>
)
