// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgActionSoundOn = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={14} height={12} viewBox="0 0 14 12" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      d="M2 4l2-4h2v12H4L2 8H1a1 1 0 01-1-1V5a1 1 0 011-1h1zM12 6a4 4 0 00-4-4V0a6 6 0 010 12v-2a4 4 0 004-4z"
      fill="#F4F6F8"
    />
    <path d="M10 6a2 2 0 00-2-2v4a2 2 0 002-2z" fill="#F4F6F8" />
  </svg>
)
