// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgGlyphInfo = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M2 8a6 6 0 1112 0A6 6 0 012 8zm5 4V7h2v5H7zm0-8v2h2V4H7z"
      fill="#F4F6F8"
    />
  </svg>
)
