// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgGlyphUpload = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M4 7l4-4 4 4M8 3v7M13 11v1a1 1 0 01-1 1H4a1 1 0 01-1-1v-1" stroke="#F4F6F8" strokeWidth={2} />
  </svg>
)
