// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY.
import styled from '@emotion/styled'
import * as React from 'react'

const SvgIcon = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <circle cx={12} cy={12} r={9} stroke="#B5C1C9" strokeWidth={2} />
    <mask id="glyph-loader_svg__a" maskUnits="userSpaceOnUse" x={2} y={2} width={20} height={20}>
      <circle cx={12} cy={12} r={9} stroke="#4038FF" strokeWidth={2} />
    </mask>
    <g mask="url(#glyph-loader_svg__a)">
      <path d="M12 0h12v24H-1l13-12V0z" fill="#4038FF" />
    </g>
  </svg>
)

export const SvgGlyphLoader = styled(SvgIcon)`
  display: block;
`
