// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgGlyphChannel = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M3 13.143V13a5 5 0 0110 0v.143a.857.857 0 01-.857.857H3.857A.857.857 0 013 13.143z" fill="#F4F6F8" />
    <circle cx={8} cy={4} r={2} fill="#F4F6F8" />
  </svg>
)
