// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgGlyphFilters = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M5.999 13h4v-2h-4v2zm-2-4h8V7h-8v2zm-2-6v2h12V3h-12z" fill="#F4F6F8" />
  </svg>
)
