// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgGlyphLoad = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <mask id="glyph-load_svg__a" mask-type="alpha" maskUnits="userSpaceOnUse" x={1} y={1} width={14} height={14}>
      <circle
        cx={8}
        cy={8}
        r={6}
        stroke="#fff"
        strokeWidth={2}
        strokeMiterlimit={14.336}
        strokeLinejoin="bevel"
        strokeDasharray="2 4"
      />
    </mask>
    <g mask="url(#glyph-load_svg__a)">
      <path d="M8 0h8v16H0l4-4 2-2H0V6l8 2-8-4V1h4l4 3V0z" fill="#F4F6F8" />
    </g>
    <mask id="glyph-load_svg__b" mask-type="alpha" maskUnits="userSpaceOnUse" x={1} y={1} width={14} height={14}>
      <circle cx={8} cy={8} r={6} stroke="#fff" strokeWidth={2} />
    </mask>
    <g mask="url(#glyph-load_svg__b)">
      <path d="M8 0h8v16H0l4-4 4-4V0z" fill="#F4F6F8" />
    </g>
  </svg>
)
