// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgGlyphLogOut = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M11 5l3 3-3 3" stroke="#F4F6F8" strokeWidth={2} />
    <path fill="#F4F6F8" d="M9 9V7h4v2z" />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M2 2a1 1 0 00-1 1v10a1 1 0 001 1h6a1 1 0 001-1V9H5V7h4V3a1 1 0 00-1-1H2z"
      fill="#F4F6F8"
    />
  </svg>
)
