// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgGlyphZoomOut = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M11 11l3 3" stroke="#F4F6F8" strokeWidth={2} />
    <path fillRule="evenodd" clipRule="evenodd" d="M8 14A6 6 0 108 2a6 6 0 000 12zM4 9h8V7H4v2z" fill="#F4F6F8" />
  </svg>
)
