// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgGlyphSearchAlt = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M11 2a9 9 0 105.618 16.032l3.675 3.675 1.414-1.414-3.675-3.675A9 9 0 0011 2zm-7 9a7 7 0 1114 0 7 7 0 01-14 0z"
      fill="#F4F6F8"
    />
  </svg>
)
