// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgGlyphSoundOff = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M9 4a4 4 0 011.587 7.673l1.483 1.483A6 6 0 009 2v2z"
      fill="#F4F6F8"
    />
    <path d="M9 9a1 1 0 000-2" stroke="#F4F6F8" strokeWidth={2} />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M3.638 4.724L7 8.086V2H5L3.638 4.724zM7 10.914L2.086 6H2a1 1 0 00-1 1v2a1 1 0 001 1h1l2 4h2v-3.086z"
      fill="#F4F6F8"
    />
    <path d="M2 2l12 12" stroke="#F4F6F8" strokeWidth={2} />
  </svg>
)
