// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgGlyphPan = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M12 6l2 2-2 2M4 10L2 8l2-2M6 4l2-2 2 2M10 12l-2 2-2-2" stroke="#F4F6F8" strokeWidth={2} />
  </svg>
)
