// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgGlyphTrash = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M2 3a1 1 0 011-1h10a1 1 0 011 1v1H2V3zM3 6h10v8a1 1 0 01-1 1H4a1 1 0 01-1-1V6z" fill="#F4F6F8" />
    <path d="M6 1h4l2 2H4l2-2z" fill="#F4F6F8" />
  </svg>
)
