// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgGlyphNewChannel = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path fillRule="evenodd" clipRule="evenodd" d="M5 8a4 4 0 00-4 4v1a1 1 0 001 1h6v-2H5V8z" fill="#F4F6F8" />
    <path d="M7 9h8M11 13V5" stroke="#F4F6F8" strokeWidth={2} />
    <circle cx={6} cy={4} r={2} fill="#F4F6F8" />
  </svg>
)
