// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgLargeUploadFailed = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={48} height={48} viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <mask id="large-upload-failed_svg__a" maskUnits="userSpaceOnUse" x={7} y={2} width={34} height={44} fill="#000">
      <path fill="#fff" d="M7 2h34v44H7z" />
      <path d="M9 44h30V14L29 4H9v40z" />
    </mask>
    <path
      d="M9 44h30V14L29 4H9v40z"
      stroke="#7B8A95"
      strokeWidth={4}
      strokeLinejoin="round"
      strokeDasharray="8 2"
      mask="url(#large-upload-failed_svg__a)"
    />
    <g>
      <mask id="large-upload-failed_svg__b" maskUnits="userSpaceOnUse" x={27} y={2} width={14} height={14} fill="#000">
        <path fill="#fff" d="M27 2h14v14H27z" />
        <path d="M29 14V4l10 10H29z" />
      </mask>
      <path d="M29 14V4l10 10H29z" fill="#7B8A95" />
      <path
        d="M29 14V4l10 10H29z"
        stroke="#7B8A95"
        strokeWidth={4}
        strokeLinejoin="round"
        mask="url(#large-upload-failed_svg__b)"
      />
    </g>
    <g stroke="#7B8A95" strokeWidth={2}>
      <path d="M19 35l5-5 5 5M29 25l-5 5-5-5" />
    </g>
  </svg>
)
