// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY.
import * as React from 'react'
export const SvgLargeUploadVideo = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={48} height={48} fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M23 36H3a1 1 0 01-1-1V9a1 1 0 011-1h30a1 1 0 011 1v16" stroke="#F4F6F8" strokeWidth={2} />
    <path d="M16 18l7 4-7 4v-8z" fill="#F4F6F8" />
    <path
      d="M34 44h-7a1 1 0 01-1-1V29a1 1 0 011-1h14a1 1 0 011 1v14a1 1 0 01-1 1h-3"
      stroke="#F4F6F8"
      strokeWidth={2}
      strokeMiterlimit={10}
      strokeLinecap="square"
    />
    <path d="M34 44V34" stroke="#F4F6F8" strokeWidth={2} strokeMiterlimit={10} />
    <path d="M31 37l3-3 3 3" stroke="#F4F6F8" strokeWidth={2} strokeMiterlimit={10} strokeLinecap="square" />
  </svg>
)
