// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY.
import * as React from 'react'
export const SvgLargeEdit = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={48} height={48} viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M8 41h32" stroke="#F4F6F8" strokeWidth={2} />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M33.693 8.693a1 1 0 00-1.4-.014l-2.143 2.057 6 6 2.114-2.03a1 1 0 00.014-1.428l-4.585-4.585zm1.014 9.428l-6-6L8 32v6h6L34.707 18.12z"
      fill="#F4F6F8"
    />
  </svg>
)
