// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY.
import * as React from 'react'

export const SvgNavChannels = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <circle cx={16} cy={7} r={3} stroke="#F4F6F8" strokeWidth={2} />
    <circle cx={6} cy={7} r={1} stroke="#F4F6F8" strokeWidth={2} />
    <path
      d="M13.5 20H21a1 1 0 001-1v-1a4 4 0 00-4-4h-4a4 4 0 00-4 4v.5M6 16h3.2a.8.8 0 00.8-.8v0A3.2 3.2 0 006.8 12H5a3 3 0 00-3 3v1"
      stroke="#F4F6F8"
      strokeWidth={2}
      strokeMiterlimit={10}
      strokeLinecap="square"
    />
  </svg>
)
