// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgNavFollowing = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      d="M10 19.313l-2.387 1.255a1 1 0 01-1.45-1.055l.748-4.367a1 1 0 00-.287-.885L3.45 11.168a1 1 0 01.554-1.705l4.385-.637a1 1 0 00.753-.547l1.96-3.972a1 1 0 011.794 0l1.96 3.972a1 1 0 00.753.547l4.385.637a1 1 0 01.554 1.705L19 12.678M23 21h-9M23 17h-9"
      stroke="#F4F6F8"
      strokeWidth={2}
      strokeMiterlimit={10}
      strokeLinecap="square"
    />
  </svg>
)
