// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY.
import * as React from 'react'
export const SvgNavNew = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      d="M1 22V4.125c0-.564.21-1.104.586-1.503A1.942 1.942 0 013 2h18c.53 0 1.04.224 1.414.622.375.399.586.94.586 1.503v10.75c0 .564-.21 1.104-.586 1.503A1.942 1.942 0 0121 17H5"
      stroke="#F4F6F8"
      strokeWidth={2}
      strokeMiterlimit={10}
      strokeLinecap="square"
    />
    <path
      d="M8.476 12.09h-1.36L4.921 8.24s.035 1.207.035 3.85H4V7h1.35l2.19 3.813S7.516 7.86 7.513 7h.963v5.09zM12.7 12.09H9.795V7H12.7v.884h-1.835v1.118h1.708v.885h-1.708v1.312H12.7v.892zM18.716 12.09h-1.218l-.683-2.673c-.05-.19-.216-.975-.235-1.192-.029.264-.173.968-.23 1.198l-.68 2.668h-1.215L13.167 7h1.053l.645 2.779c.112.513.194.957.245 1.334.102-.673.693-3.067.97-4.113h1.01l.736 2.852c.074.295.189.943.232 1.26.047-.377.169-1.015.248-1.334L18.948 7H20l-1.284 5.09z"
      fill="#F4F6F8"
    />
  </svg>
)
