// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY.
import * as React from 'react'

export const SvgNavPopular = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      d="M17.292 9C19 10 20 12.61 20 15c0 3.012-1.54 5.635-4 7h-1c0-6-2.452-6-4-6 0 2-.6 6-3 6-2.46-1.365-4-3.988-4-7 0-1.892.657-3.63 1.755-5C7 8 11 6 11 2h1c1.485 1.788 3.274 6.158 1 9"
      stroke="#F4F6F8"
      strokeWidth={2}
    />
  </svg>
)
