// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgNavSettings = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      d="M20 12a8.023 8.023 0 00-.188-1.713l2.01-1.522a1 1 0 00.263-1.297l-1.118-1.936a1 1 0 00-1.254-.42l-2.33.982a7.984 7.984 0 00-2.961-1.719l-.313-2.5A1 1 0 0013.117 1h-2.234a1 1 0 00-.993.876l-.312 2.499c-1.1.352-2.11.939-2.961 1.719l-2.33-.983a1 1 0 00-1.254.421L1.915 7.468a1 1 0 00.263 1.297l2.01 1.522a7.888 7.888 0 000 3.426l-2.01 1.522a1 1 0 00-.263 1.297l1.118 1.936a1 1 0 001.254.42l2.33-.982a7.983 7.983 0 002.961 1.719l.312 2.5a1 1 0 00.993.875h2.234a1 1 0 00.992-.876l.313-2.499a7.983 7.983 0 002.961-1.719l2.33.983a1 1 0 001.254-.421l1.118-1.936a1 1 0 00-.263-1.297l-2.01-1.522A8.023 8.023 0 0020 12z"
      stroke="#F4F6F8"
      strokeWidth={2}
      strokeMiterlimit={10}
      strokeLinecap="square"
    />
    <circle cx={12} cy={12} r={3} stroke="#F4F6F8" strokeWidth={2} />
  </svg>
)
