// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgOutlineConnect = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path fill="#F4F6F8" d="M1 11h7v2H1zM16 11h7v2h-7z" />
    <circle cx={10} cy={12} r={3} stroke="#F4F6F8" strokeWidth={2} />
    <path d="M10 19a7 7 0 100-14" stroke="#F4F6F8" strokeWidth={2} />
  </svg>
)
