// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgOutlineLoader = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={32} height={32} viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <circle cx={16} cy={16} r={15} stroke="#DAE2EB" strokeWidth={2} />
    <mask id="outline-loader_svg__a" mask-type="alpha" maskUnits="userSpaceOnUse" x={0} y={0} width={32} height={32}>
      <circle cx={16} cy={16} r={15} stroke="#4038FF" strokeWidth={2} />
    </mask>
    <g mask="url(#outline-loader_svg__a)">
      <path d="M16 0h16v32H.5L16 16V0z" fill="#4038FF" />
    </g>
  </svg>
)
