// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgOutlineError = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={32} height={32} viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <circle cx={16} cy={16} r={15} stroke="#FF3861" strokeWidth={2} />
    <path d="M11 21l10-10M21 21L11 11" stroke="#FF3861" strokeWidth={2} />
  </svg>
)
