// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgOutlineFileVideo = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M2 5a1 1 0 011-1h18a1 1 0 011 1v1h-2v2h2v8h-2v2h2v1a1 1 0 01-1 1H3a1 1 0 01-1-1V5zm6 1h2v2H8V6zm6 0h-2v2h2V6zm2 0h2v2h-2V6zM8 16h2v2H8v-2zM6 6H4v2h2V6zM4 16h2v2H4v-2zm14 0h-2v2h2v-2zm-6 0h2v2h-2v-2z"
      fill="#F4F6F8"
    />
  </svg>
)
