// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgOutlineWarning = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={32} height={32} viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <circle cx={16} cy={16} r={15} stroke="#F3901C" strokeWidth={2} />
    <path d="M16 18v-8M16 22v-2" stroke="#F3901C" strokeWidth={2} />
  </svg>
)
