// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY.
import * as React from 'react'

export const SvgPlayerForwardFiveSec = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={72} height={72} viewBox="0 0 72 72" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <g filter="url(#player-forward-five-sec_svg__filter0_b)">
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M36 12c13.255 0 24 10.745 24 24h6C66 19.431 52.569 6 36 6v6zM24 27l12 9-12 9V27zm15 0l12 9-12 9V27z"
        fill="#F4F6F8"
      />
    </g>
    <defs>
      <filter
        id="player-forward-five-sec_svg__filter0_b"
        x={-32}
        y={-32}
        width={136}
        height={136}
        filterUnits="userSpaceOnUse"
        colorInterpolationFilters="sRGB"
      >
        <feFlood floodOpacity={0} result="BackgroundImageFix" />
        <feGaussianBlur in="BackgroundImage" stdDeviation={16} />
        <feComposite in2="SourceAlpha" operator="in" result="effect1_backgroundBlur" />
        <feBlend in="SourceGraphic" in2="effect1_backgroundBlur" result="shape" />
      </filter>
    </defs>
  </svg>
)
