// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgPlayerShare = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M20 12l-8-6v4h-2c-4 0-6 2-6 5v1h2v-1a1 1 0 011-1h5v4l8-6z"
      fill="#F4F6F8"
    />
  </svg>
)
