// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY.
import * as React from 'react'

export const SvgPlayerLoaderFallback = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={144} height={144} viewBox="0 0 144 144" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <g clipPath="url(#player-loader-fallback_svg__clip0)" fillRule="evenodd" clipRule="evenodd" fill="#fff">
      <path d="M143.999 143.999l-.004.001-.25-15.997C135.025 128.139 128 135.254 128 144h15.995l-.002.001h-.004m0 0h.006V144c.001 0 0 0 0 0l.004-.001-.003.006a.004.004 0 01-.001.003l.006-.007.006-.005s0-.001 0 0l-.002.001-.005.002v-.007.002l-.001.005M144 112c-17.658 0-32 14.342-32 32H96c0-26.494 21.506-48 48-48v16z" />
      <path d="M144 80c-35.319 0-64 28.681-64 64H64c0-44.155 35.845-80 80-80v16z" />
      <path d="M144 48c-52.98 0-96 43.02-96 96H32C32 82.184 82.184 32 144 32v16z" />
      <path d="M144 16C73.36 16 16 73.36 16 144H0C0 64.524 64.524 0 144 0v16z" />
    </g>
    <defs>
      <clipPath id="player-loader-fallback_svg__clip0">
        <path fill="#fff" d="M0 0h144v144H0z" />
      </clipPath>
    </defs>
  </svg>
)
