// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgPlayerCastOn = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M3 3a2 2 0 00-2 2v6h2V5h18v14H11v2h10a2 2 0 002-2V5a2 2 0 00-2-2H3zM1 15a6 6 0 016 6h2a8 8 0 00-8-8v2zm2 6a2 2 0 00-2-2v-2a4 4 0 014 4H3zm2-10v.832A10.037 10.037 0 0110.168 17H19V7H5v4z"
      fill="#F4F6F8"
    />
  </svg>
)
