// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY.
import * as React from 'react'

export const SvgPlayerSoundOff = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M21.222 20.808l-18-18" stroke="#F4F6F8" strokeWidth={2} strokeMiterlimit={10} />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M14.899 15.899A4.002 4.002 0 0014 8v2a2 2 0 110 4v1l.899.899zM5.172 9H3a1 1 0 00-1 1v4a1 1 0 001 1h3l4 5h2v-4.172L5.172 9zM12 13V4h-2L6.889 7.889 12 12.999z"
      fill="#F4F6F8"
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M14.17 17.998A6.362 6.362 0 0114 18v2a8.02 8.02 0 001.936-.236l-1.767-1.766zm3.786.957A8 8 0 0014 4v2a6 6 0 012.47 11.47l1.486 1.485z"
      fill="#F4F6F8"
    />
  </svg>
)
