// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY;
import * as React from 'react'

export const SvgPlayerPlaylist = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M17 15l5 3-5 3v-6z" fill="#F4F6F8" />
    <path d="M18 12H2M18 8H2M15 16H2" stroke="#F4F6F8" strokeWidth={2} strokeMiterlimit={10} />
  </svg>
)
