// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY.
import * as React from 'react'

export const SvgVideoCategoriesSports = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={22} height={14} viewBox="0 0 22 14" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M12.5 2.669A4.977 4.977 0 0115 2c.91 0 1.765.244 2.5.669a6.973 6.973 0 00-1.5 4.33c0 1.636.561 3.14 1.5 4.332-.735.425-1.589.669-2.5.669a4.976 4.976 0 01-2.5-.67A6.973 6.973 0 0014 7c0-1.635-.561-3.14-1.5-4.331zM11 3.999c-.628.836-1 1.875-1 3.001s.372 2.165 1 3c.629-.836 1-1.874 1-3a4.975 4.975 0 00-1-3zm7 3c0-1.125.371-2.164 1-3 .628.836 1 1.875 1 3.001a4.978 4.978 0 01-1 3 4.975 4.975 0 01-1-3zM15 0a7 7 0 100 14 7 7 0 000-14zM7 2H3v2h4V2zM3 12v-2h4v2H3zm3-4V6H0v2h6z"
      fill="#F4F6F8"
    />
  </svg>
)
