// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY.
import * as React from 'react'

export const SvgVideoCategoriesGaming = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={22} height={18} viewBox="0 0 22 18" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M10 0h2v2h-2V0zM3.5 6.576A3 3 0 016.47 4h.116l1.707 1.707.293.293H13.414l.293-.293L15.414 4h.117a3 3 0 012.97 2.576l1.123 7.86a1.37 1.37 0 01-2.495.954l-1.297-1.945-.297-.445h-9.07l-.297.445L4.87 15.39a1.37 1.37 0 01-2.495-.953L3.5 6.576zM6.47 2a5 5 0 00-4.95 4.293L.395 14.154a3.37 3.37 0 006.14 2.346l1-1.5h6.929l1 1.5a3.37 3.37 0 006.139-2.346L20.48 6.293A5 5 0 0015.53 2H14.586l-.293.293L12.586 4H9.414L7.707 2.293 7.414 2H6.47zM7 7H5v2h2V7zm10 0h-2v2h2V7z"
      fill="#F4F6F8"
    />
  </svg>
)
