// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY.
import * as React from 'react'

export const SvgVideoCategoriesNonprofitsAndActivism = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={20} height={22} viewBox="0 0 20 22" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M8 4a1 1 0 00-2 0v2a1 1 0 002 0V4zm3 3a1 1 0 01-1-1V3a1 1 0 112 0v3a1 1 0 01-1 1zm2.493-5.67A2.997 2.997 0 0011 0a2.998 2.998 0 00-2.529 1.385 2.998 2.998 0 00-4 1A3 3 0 000 5v8a9 9 0 009 9h2v-2H9a7 7 0 01-7-7V8.83c.313.11.65.17 1 .17.768 0 1.47-.289 2-.764C5.53 8.711 6.232 9 7 9c.462 0 .9-.105 1.291-.291A3 3 0 0011 13h2.809c.095 0 .126.028.138.04a.232.232 0 01.062.133.233.233 0 01-.02.146c-.009.014-.03.05-.122.077l-1.17.35A2.381 2.381 0 0011 16.029V18h2v-1.972c0-.169.11-.317.272-.365l1.17-.351c2.43-.73 1.904-4.312-.633-4.312H11a1 1 0 110-2h6a1 1 0 011 1v3a7.003 7.003 0 01-5 6.71v2.067c4.008-.91 7-4.494 7-8.777v-3a3.001 3.001 0 00-2-2.83V4a3 3 0 00-3-3h-.182c-.479 0-.93.12-1.325.33zM2 5v1a1 1 0 002 0V5a1 1 0 00-2 0zm14-1a1 1 0 10-2 0v2a1 1 0 102 0V4z"
      fill="#F4F6F8"
    />
  </svg>
)
