// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY.
import * as React from 'react'

export const SvgVideoCategoriesFilmAndAnimation = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M15 2h-2v4h2V2zm-1 8a2 2 0 100 4 2 2 0 000-4zm-4 2a4 4 0 017.465-2H20a2 2 0 012 2v6a2 2 0 01-2 2h-2v2h-2v-2H8v2H6v-2H4a2 2 0 01-2-2v-6a2 2 0 012-2h4v2H4v6h16v-6h-2a4 4 0 01-8 0zm-2 2H6v2h2v-2zM6.222 5.636l1.414-1.414 2.828 2.828L9.05 8.464 6.222 5.636zm15.557 0l-1.415-1.414-2.828 2.828 1.414 1.414 2.829-2.828z"
      fill="#F4F6F8"
    />
  </svg>
)
