// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY.
import * as React from 'react'

export const SvgVideoCategoriesAutosAndVehicles = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={22} height={16} viewBox="0 0 22 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M6.547 2.725A1 1 0 017.51 2h7.05a1 1 0 01.948.684l.544 1.632.228.684H19.5V3h-1.78l-.316-.949A3 3 0 0014.56 0h-7.05a3 3 0 00-2.885 2.176L3.246 7H2a2 2 0 00-2 2v4a3 3 0 003 3h.93a3 3 0 002.496-1.336L7.536 13h6.929l1.11 1.664A3 3 0 0018.07 16H19a3 3 0 003-3V9a2 2 0 00-2-2H5.326l1.221-4.275zM2 9v4a1 1 0 001 1h.93a1 1 0 00.832-.445l1.11-1.664A2 2 0 017.534 11h6.93a2 2 0 011.664.89l1.11 1.665a1 1 0 00.831.445H19a1 1 0 001-1V9H2z"
      fill="#F4F6F8"
    />
  </svg>
)
