// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY.
import * as React from 'react'

export const SvgVideoCategoriesPeopleAndBlogs = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={22} height={18} viewBox="0 0 22 18" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M14 16v2h2v-2a2 2 0 00-2-2H8a2 2 0 00-2 2v2h2v-2h6zM4 14H2V2h18v12h-2v2h2a2 2 0 002-2V2a2 2 0 00-2-2H2a2 2 0 00-2 2v12a2 2 0 002 2h2v-2zm5-6a2 2 0 114 0 2 2 0 01-4 0zm2-4a4 4 0 100 8 4 4 0 000-8z"
      fill="#F4F6F8"
    />
  </svg>
)
