// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY.
import * as React from 'react'

export const SvgVideoCategoriesScienceAndTechnology = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M6 11a7 7 0 0114 0v.338a5 5 0 01-.713 2.573l-1.29 2.15a7 7 0 00-.997 3.6V20h2v-.338a5 5 0 01.712-2.573l1.29-2.15a7 7 0 00.998-3.6V11a9 9 0 00-18 0v1.667L2.4 14.8C1.411 16.119 2.352 18 4 18v2a2 2 0 002 2 9.001 9.001 0 008.961-8.157A3.001 3.001 0 0014 8a3 3 0 00-1.047 5.812A7.001 7.001 0 016 20v-4H4l1.8-2.4.2-.267V11zm7 0a1 1 0 112 0 1 1 0 01-2 0z"
      fill="#F4F6F8"
    />
  </svg>
)
