// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY.
import * as React from 'react'

export const SvgVideoCategoriesEntertainment = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={18} height={21} viewBox="0 0 18 21" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M9.515.34A2 2 0 0112 2.28V4h-2V2.28L3.825 3.826 2.28 10H6v8.453L15.707 8H10V6h5.707c1.746 0 2.654 2.081 1.465 3.36L7.466 19.815C6.229 21.146 4 20.271 4 18.454V12H2.28A2 2 0 01.34 9.515L1.884 3.34A2 2 0 013.34 1.884L9.515.34z"
      fill="#F4F6F8"
    />
  </svg>
)
