// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY.
import * as React from 'react'

export const SvgVideoCategoriesScienceAndTechnology = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={21} height={20} viewBox="0 0 21 20" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M5 9a7 7 0 0114 0v.338a5 5 0 01-.713 2.573l-1.29 2.15a7 7 0 00-.997 3.6V18h2v-.338a5 5 0 01.712-2.573l1.29-2.15A7 7 0 0021 9.34V9A9 9 0 003 9v1.667L1.4 12.8C.411 14.118 1.352 16 3 16v2a2 2 0 002 2 9.001 9.001 0 008.961-8.157A3.001 3.001 0 0013 6a3 3 0 00-1.047 5.812A7.001 7.001 0 015 18v-4H3l1.8-2.4.2-.267V9zm7 0a1 1 0 112 0 1 1 0 01-2 0z"
      fill="#F4F6F8"
    />
  </svg>
)
