// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY.
import * as React from 'react'

export const SvgVideoCategoriesPetsAndAnimals = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={22} height={22} viewBox="0 0 22 22" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M15.625 1.22L14.598.397l-.517 1.208L11.34 8H5a3 3 0 01-3-3H0a4.998 4.998 0 002.505 4.334A2.986 2.986 0 002 11v11h2V11a1 1 0 011-1h7.66l.26-.606 2.482-5.792 1.473 1.179.274.219h2.718a3 3 0 01-1.918 1.963l-.265.088-.598.2-.078.625-1 8-.008.062V20h4v-2h-2v-1.938l.916-7.327A5 5 0 0022 4.117V3h-4.15l-2.225-1.78zM6 19v3h2v-3.288l1.489-3.35L12 16.618V22h2v-6.618l-.553-.276-4-2-.936-.468-.425.956-2 4.5-.086.194V19z"
      fill="#F4F6F8"
    />
  </svg>
)
