// THIS FILE WAS AUTOGENERATED BY SVGR. DO NOT MODIFY IT MANUALLY.
import * as React from 'react'

export const SvgVideoCategoriesFilmAndAnimation = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width={20} height={20} viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M13 0h-2v4h2V0zm-1 8a2 2 0 100 4 2 2 0 000-4zm-4 2a4 4 0 017.465-2H18a2 2 0 012 2v6a2 2 0 01-2 2h-2v2h-2v-2H6v2H4v-2H2a2 2 0 01-2-2v-6a2 2 0 012-2h4v2H2v6h16v-6h-2a4 4 0 01-8 0zm-2 2H4v2h2v-2zM4.222 3.636l1.414-1.414L8.464 5.05 7.05 6.464 4.222 3.636zm15.557 0l-1.415-1.414-2.828 2.828 1.414 1.414 2.829-2.828z"
      fill="#F4F6F8"
    />
  </svg>
)
